#+TITLE: O Gloriosa Domina

|------------+-------------------|
| Manuscript | AM08-0073         |
| Locus      | 67r 67v           |
| Work       | O_GLORIOSA_DOMINA |
| Language   | gml               |
| Status     | transcribed       |
|------------+-------------------|

* Transcription
** Rubric
O gloriosa domina.

** Text
[[red 2][O]] aller hogiste vrowe up

gehoghet bouen alle

hemele de dre stup de soge de

dine hilgen brust. [[red][D]]at eua

bedruuelike vns nam dat

hefstu vns wedder genen.

myt dynen bloge uden ly

chame se gan wenelichen

inde pyne. du bist wurden

en hemeles vinster. [[red][O]] mari

a du byst des hogesten ko

ninges dore. vnd(e) syn lichte

skinende porte de wurvro

we heft vns dat lyf ge ghe

--- 67v---

uen de lude de loset syn de vro

wen syt. [[red][M]]aria m(ate)r. [[red][O]] ma

ra ???der. [[red][O]] here de ere sy

[[red][G]]ot kos maria vt vor

** Antiphony
*** Rubric
an(tiphonia)

*** Text
allen. vnd(e) let se wonen in

syneme tabernaculo.

** Collect
*** Rubric
sub t[??]

*** Text
[[red][O]] maria godes moder we

vlen vnder dyne beschermynge

vnse bet vor sma nicht in

vnser behofnisse den van

aller vare vn(de) bedrofnis

se lose vns ewykliken bene

dyde iu(n)curowen.
