#+TITLE:

|------------+-----------|
| Manuscript | AM 72 8vo |
| Locus      | 128r      |
| Work       |           |
| Language   | da        |
| Status     | copied    |
|------------+-----------|

* Transcription
** Rubric
hær nest stonn(er) jen god

bøn aff iomfrw maria.

** Text
I eg hælser theg alth hellisthe mother gws angels frw och droth- ningh meth then hielsen som *gabriel engel hielsset thigh || 129r then tidh han sawdhe: hel maria fwl meth nothe, wor herræ er meth theg, then helgeand skal owen komme i theg, then al howesth gusdz dygh om *skøghe thig, thet *hælith for thy *som skal føthis aff thig skal kallis gus son; iek bether theg widh then glethe hwlken thw hafthen naath ther thw fødhe thin son wor 15 herræ ihesus christus, hwilken thw fødhe wthen al sorgh, oc thw vnfeth wthen al mans sedh, at thw gledh meg i alle myne bedrøwels oc alle myne engsel nødhthørth och al myne armoth for then skyl. O helghe frwa iomfrw sancta maria, i thin tro, i 129 thin milheth, i thin miscwnnelykthet befaler jek megh wwer- 20 theghe thener, och bether iek thegh, rose ower alla rosa, ath fredh worther ower megh i dagh, hwilken fredh ower theg war then nath som thu fodthe thin helghe søn ihesum christum, amen. 
25 
** Rubric
collecte 
GYiff ath ieg bliwer beskermith aff alt wnth og aff alle *falskæ 
twnghe oc aff all *werdens løwen oc aff all brad døth, thin werdwghedh war besloth oc ær ewinnelikt. Amen. 
so som
