#+TITLE: Cantus Sororum (Matins)

|------------+---------------|
| Manuscript | AM 70 8vo     |
| Locus      | 3r            |
| Work       | CANTUS.matins |
| Language   | gml           |
| Status     | begun         |
|------------+---------------|

* Transcription
** Text
bekoreden juwe vedere se prouede vnde

seghen myne werke. 

** Psalm
*** Rubric
Quadraginta

*** Text
[[blue 2][U]]ertich jar was ik by desser telinge

vnde sede alle tijt se dweleden an

deme herten. Men se bekanden nicht

myne weghe den ik hebbe sworen an

myneme torne se scholen nicht ghan

in myne rouwe. 

*** Rubric
Gl(ori)a pat(ri) 

*** Text
Ere sy de(me)

vadere vnde deme sone vnde deme hilli-

ghen gheste. [[green][A]]lse id was an deme

anbeghynne vnde nv vnde alle tid to

ewighen tiden Amen. 

** Hymn
*** Rubric
ympnus.

*** Text
[[red 2][O]] du ere derhillighen drevaldicheit.

du syrnighe des hemelschen hoůes

du brut des allerhoghesten konynges

vnde ene moder synes sones [[blue][G]]ot de

heft dy ghehillighet van ambegy(n)ne

ene konynghynnen der ere vnde heft

dy vullenkomen maket ene vrouwe

bouen alle dingh. [[red][H]]ir vi(n)ne de hemele

dat ertrike dat mer vnde wat dar jnne

is. de louen dy myt rechteme rechte

alse a(n)name deme hoghesten heren

[[green][D]]u juncvrouwe alder a(n)nameste

---3v---

gode bouen alle dynk de he heft ghe-

schapen make vns anname eme de

he heft gheloset myt syme blode [[red][M]]a-

ria du modher der gnadenmodher der

barmherticheit bescherme vns vor

den viand in der stunde des dodes nym

vns to dy. [[green][E]]re sy dy here de du bist

gheboren van der juncvrouwen myt

⸠myt⸡ deme vadere vnde myt deme hilge(n)

geste to ewighen tyden Amen

** Verse?
*** Rubric
¶

*** Text
[[blue 2][O]] du leflike juncvrouwe van gode

vp synen hillighen berch syon ge-

stedighet ene konyngynne make vns

denende dy neme sone in vrůchten

vnde ene hoghelouen myt beuynge

** Psalm
*** Rubric
psalmus

*** Text
[[red 3][W]]or v(m)me gry(m)meden

de lude: vnde dat volk de dachten

de ydelheit. [[green][D]]e erdeschen ko-

nynge vnde de vursten quemen to

samen: jegen dan heren vnde tiegen

cristo. [[blue][W]]y breken ere bende: vnde wer-

pen van vns ere / [[red][D]]e dar wonet

an den hemele de schal se bespotten:

vnde vns here schal se besch⸠e⸡⸌y⸍mpen

---4r---

[[green][D]]enne schal he to en spreken in syne(n)

torne: vnde in syme v(m)mode wil he se

bedrouen. [[red][S]]under ik byn eyn konynk

ghesettet van eme vpp synen hilligen

berch syon. to kůndeghen syn bot ~

[[blue][G]]ot sprak to my du bist myn sone:

huten ghebar ik dy. [[red][B]]idde van my

ik gheue dy volk dyne erue: vnde de

ende der werelt stät an dyner walt.

[[green][D]]u scholt se righten an eyner yseren

roden: vnde schalt se to breken also

enen erdenen gropen [[blue][U]]nde nv mer-

ket gy konynge: vnde werdet gheleret

gy de dar ordelen de erden. [[red][D]]enet de(me)

heren myt vruchten: vn(de) vrouwet 

jw vor em myt beuynge. [[blue][G]]ripet de

tucht vppe dat sik de here nicht en tor-

ne: |-vn(de)_vorwe-| uppe dat. dat gy nichte(n)

vorgän van deme rechten weghe.

[[green][W]]en er syn torne in korten bernet:

salich synt de. de an em louen. [[red][E]]re

sy deme vader 

** Antiphone
*** Rubric
Antiphona.

*** Text
[[blue 2][O]] entfanger vnde ere der junc-

vrouwen. maria sta vp jegen

---4v---

vnse weddersaten. vnde dyne be-

nediginghe kome vppe dyn volk

** Psalm
*** Rubric
psalmus

*** Text
[[red 2][H]]Ere wor v(m)me

synt ghemeret de jene(n) de my

bedrouen: der is vele de my tiege(n)

stan [[blue][U]]ele de seden dat in myner

selen were neyn heyle synes godes.

[[red][S]]under du here entfangest my:

du bist myn ere vnde vorhogest my(n)

houet. [[green][J]]k rep to gode myt myner 

stempne. vnde he twide my van

synen hilligen berge. [[red][I]]k slep vn(de)

rouwede vnde stunt vp wente got 

entfingh my. Jk schal nicht vru-

chten dusent volkes dat se my be-

gripen: here got staa vpp vn(de) make

my salich myn got. [[red][W]]ente du hest 

gheslaghen alle myne wedder sate(n)

my sunder sake: de tenen der sunder

hestu to broken [[green][U]]nses heren is

dat heil vnde vp dyne volk kome

dyn benediginghe. [[red][E]]re sy deme

vader vnde deme sone vn(de) deme hil-

lighen gheste. Alse i{s/t} was (et_cetera)

---5r---

*** Antiphon
**** Rubric
Antiphona Jnt(er)ueniente te (et_cetera)

**** Text

[[red 2][O]] du telerynne godes myt dyne(n)

bede so make vns gode werdich

eme to offerende dat offer der recht-

uerdicheit uppe welkere dat licht

synes antlates is getekent.

** Psalm
*** Rubric
Psalmus

*** Text
[[blue 2][G]]ot myner rechticheit du hordest

my do ike dy an rep an myner

not hestu my ghebreydet [[red][G]]nade

my vn(de) hore myn ghebet [[green][D]]er lude

kyndere wo lange beswaret van

herten wor v(m)me gy leff hebben de

ydelheit unde soken de droghen [[red][G]]y

scholen weten dat vnse here won-

derlike heft ghemaket syn hilligen

myn here schal my horen wen ik

to em rope [[blue][T]]ornet jw vn(de) sunde-

ghet nicht de ghy seggen an jw her-

ten vnde rouwet jw an juwer le-

gheringhe. [[red][O]]ffert dat offer der rech-

ticheit vnde hopet an vnsen heren

me(n)nich spreket we wiset vns da gna-

de. [[blue][H]]ere dynes antlates \licht/ is tekent

bouen vns du hest de vroude ghe-

---5v---

gheuen mynen herten. [[red][U]]an der vrucht

des weytens. mynes vnde olyes synt

se mennichuoldighet [[blue][D]]ar v(m)me schal

ik slapen vnde rouwen an de(n) vrede.

[[red][W]]ente du here hest my sunderliken

gheschicket an dyne hopene [[green][E]]re sy de(me)

*** Versicle
**** Rubric
Versiculus.

**** Text

[[blue][D]]{d/}u konyngynne der

hemele boghe dyn ore to vns. Dar

sik hest to gheboghet vor vns de here

der heren. P(ate)r noster. Et ne nos

*** Responsonory
**** Rubric
pre-

cibus (et) meritis.

**** Text
[[red][U]]mme des bedes vn(de)

vordenstes willen der alderhilligisten

godes telerinnen der juncrouwen

marien vnde allerhillighen bescher-

me vnde salichmake vns de mylde va-

der vn(de) barmhertighe here. Amen.

*** Absolution
**** Rubric

Absolucio. Su(m)me trinitati v(ir)go g(ra)cissi(m)a

**** Text

[[blue][D]]e alde a(n)nameste iuncvrouwe der

hoghen dreualdicheit. De bescher-

me vns vnder ereme alder werdi-

geste bede. Amen

* Lessons
** Rubric
Jn dessen dren lexe(n)

bewist de engel wo got de erwerdege(n)

juncvrouwen syne moder marien

hadde leff bouen alle creature

---6r---

** Lesson
*** Rubric
l(ec)c(i)e p(rima). de erst lexie

*** Text
[[red blue 5][D]]at wort 

dat sunte joha(n)nes ewan-

gelista in syne(m) ewangelio

dachtnysse van deit. DSat

was van ambegynne myt

deme vader vnde myt deme hillighen

geste eyn got. Wente dre synt der per-

sonen vnde eyn is in en eyne vulko-

mene gotheit. vnde desse dre persone(n)

weren in allen ghelike. Wente en

was allen, eyn wille, eyn wisheit eyn

macht, eyn schönheit eyn doghet,

eyn leue, eyn vrouwede. Vorwar v(n)-

mogelik hadde dat ghewesen dat

dat wort hedde got gheweset wen

id were van deme vadere vnde van

deme hillighen gheste to sünder ende

Alse men van deme worde. Jta. dat

de warheit bedüdet. Vnde in sik holt

dre bokstaue mach men alsulke like-

nysse aff hebben. Alse ofte eyn van

den dren bokstaue(n) wurde aff ghenome(n)

van den andere(n). So en hadden se nicht

de macht dese touoren hedden. Vnde

---6v---

makeden nicht dat sulue wort. Des

ghelikes schal me(n) vorneme(n) van de(n)

dren persone(n) in eyner gotheit. Wen-

te were jenich p(er)son to sünderende

van den anderen. edder dan andere(n)

vngelike. edder wor ane brochsam

dat de andere hebben. so were an en

nene gotheit. Wente de gotheit is

an sik vndeylaftich. vnde ok in der

entfanginge der mynscheit. Wen-

te dat wort is de sone godes. vn(de)

dat dat wort van deme vadere vn(de)

van deme hilligen geiste scholde

hebben weset ghedylet. Dat steit

nicht to louende. Wente rechte 

alse eyn wort dat wy spreken alley-

ne dat it wert ghedacht in deme

herten vnde wert ghesproken myt

deme munde noch en mach dat nicht

ghetastet werden nogh gheseen. dat

en wurde deme ghedrucket edder 

ghescreuen an eyn materilik dynk

Also ok dat wort dat is de sone godes

v(m)me salicheit des mynsche(n) slech-

---7r---

tes an to tastende edder seen hadde

vnmoghelik ghewest. hadde he sik

nicht myt der mynchselik nature

nycht vorenyghet. Vnde ok des

ghelikes wen eyn wort wert gheseen

ghescreuen in eneme boke. dat mach

in deme herte werden betrachtet vn(de) 

ok myt deme munde werden ghespro-

ken. Also vorware de sone godes sicht-

like in der mynscheit de he to sik ghe-

nomen hadde vn(de) allike wol wesen

myt deme vadere vnde myt deme hil-

ligen gheste. dar schal nement an

twyuelen. Vn(de) dar v(m)me synt war-

liken dre personen vnsünderlik vnd(e)

vnwandelik ewichliken in allen ghe-

liken eyn got. Vnde vorwar in deme

gode weren alle dink van ambegy(n)ne

vorgheweten. Alle dink weren vor

syneme anghesichte myt schonheit

erwerdichliken eme to vrouwede

vnde to eren de he dar negest hadde

do dat eme behagede myt scheppen

de ghar klokliken brachte in eyn

---7v---

wesent. Wente van nener vöt. noch

vroude edder des ghemakes dat eme

mochte hebben enbroken war got

wat to scheppende ghedwunghen.

Wente dat was vnmoghelik dat he

an sik welk ghebrech scholde hebbe(n)

gheleden. Vnde dar v(m)me syne ber-

nende leue toch en to scheppende vppe

dat erer vele myt eme in syner vnspre-

keliker vroude ewichliken mochte vor-

hoghen. Vnde dar v(m)me dat alle creature

de he wolde schape in sodaner scaltnisse

vnde wyse_schop he dar negest ghar

schone also se vor syme angesichte

schone stunden vngheschapen. Jo

doch vnder allen de do noch nicht en we-

ren gheschapen. So was eyn vor gode

dat ouer alle de andere(n) trat des he sik

suluen sere vrouwede. Wente in de(me) 

vnghapene(n) de vere elementen Also

vür. de lucht. dat water. vnde de erde.

allene dat de noch nychten were(n) ghe-

schapen. Jn sodaner mate openbareden

sik deme gotliken anghesichte ewich-

---8r---

liken Also dat de luch also lichtuorich

scholde werden dat de tiegh den hilli-

ghen gheest nümmer scholde blasen.

Vnde dat ertrike in deme vnghescha-

penen scholde gheschapen werden also

gut vnde also vruchtbar dat nicht 

vt der erden mochte wassen dat to alle(n)

dingen nicht nütte en were. Dat

water scholde also bequeme werden dat

vte wat wynkel de storm des wyndes

queme edder bewegede nene bulghen

konde in deme vngheschapene(n) dinghe 

yenigerleye wijs beweghet werden.

Vnde ok dat vür also hoch myt syner

vlammen vnde hette mochte nalen de(me)

huse dar got sulue(n) jnne was. O ma-

ria aller schoneste juncvrouwe vnde

vruchtbareste moder, dat vnghescha-

pene do noch dat bystu. Wente du

alsodane stundest noch vngeschapen

van ambegynne vor deme anghesichte

godes. Vnde dar negest van den claren

puren elementen vorbenomet haddestu

de nature dynes benediden lichames

---8v---

Vorware alsodane stundestu vor gode

er dyner scheppinge vngheschapen.

Alse du dar negest vordenedest to wer-

dende. Vnde dar v(m)me van ambegynne

all dat schapen scholde werden vor de(me)

anghesichte godes. dat gyngestu Maria

all en bouene. Wente got de vader dyner

vruchtbaren werke de du myt syner hul-

pe scholdest dön was des sere ghevrou-

wet. De sone dyner vruchtbare stedic-

heit. vnde de hillighe gheest dynes ot-

modighen horsames weren ok ghe-

vrouwet. Jo doch so was deme vadere

vrouwede des sones vnde des hillighen 

gheistes. Vnde ok deme hillighen ghes-

te was vroude des vaders vnde des sones

Vnde dar v(m)me alse en allen van dy was

eyn vroude Also hadden se to dy alle

eyne leue. Tu autem d(omi)ne miserere n(ost)ri

*** Responsory
**** Rubric

Responsorium sequitur

**** Text
[[green 2][D]]er alderhogesten drevaldicheit de(me)

entvoldighen gode is eyn gotheit

ghelike ere. ewyghe ghelike walt deme

vadere vnde deme sone vnde deme hilli-

---9r---

ghen gheste. De de gantze werelt heft vn-

derdan synen gheboden. 

*** Versicle
**** Rubric
V(ersiculus)

**** Text
De dreualdi-

ghe vnde ene got geue vns de gnade deme

du o maria van ambegynne alderhogest

hest behaghet. De de gantze werelt.

*** Absolution
**** Rubric

Absolucio. Gutturre nobis mater

**** Text

[[blue][K]]om vns to hulpe moder cristi. de du hest

inghebracht de vroude der bedrouede(n) werlt

Amen.
