#+TITLE: Cantus Sororum (Matins)

|------------+---------------|
| Manuscript | AM 70 8vo     |
| Locus      | 3r            |
| Work       | CANTUS.matins |
| Language   | gml           |
| Status     | begun         |
|------------+---------------|

* Transcription
** Text
bekoreden juwe vedere se prouede vnde

seghen myne werke. 

** Psalm
*** Rubric
Quadraginta

*** Text
[[blue 2][U]]ertich jar was ik by desser telinge

vnde sede alle tijt se dweleden an

deme herten. Men se bekanden nicht

myne weghe den ik hebbe sworen an

myneme torne se scholen nicht ghan

in myne rouwe. 

*** Rubric
Gl(ori)a pat(ri) 

*** Text
Ere sy de(me)

vadere vnde deme sone vnde deme hilli-

ghen gheste. [[green][A]]lse id was an deme

anbeghynne vnde nv vnde alle tid to

ewighen tiden Amen. 

** Hymn
*** Rubric
ympnus.

*** Text
[[red 2][O]] du ere derhillighen drevaldicheit.

du syrnighe des hemelschen hoůes

du brut des allerhoghesten konynges

vnde ene moder synes sones [[blue][G]]ot de

heft dy ghehillighet van ambegy(n)ne

ene konynghynnen der ere vnde heft

dy vullenkomen maket ene vrouwe

bouen alle dingh. [[red][H]]ir vi(n)ne de hemele

dat ertrike dat mer vnde wat dar jnne

is. de louen dy myt rechteme rechte

alse a(n)name deme hoghesten heren

[[green][D]]u juncvrouwe alder a(n)nameste

---3v---

gode bouen alle dynk de he heft ghe-

schapen make vns anname eme de

he heft gheloset myt syme blode [[red][M]]a-

ria du modher der gnadenmodher der

barmherticheit bescherme vns vor

den viand in der stunde des dodes nym

vns to dy. [[green][E]]re sy dy here de du bist

gheboren van der juncvrouwen myt

⸠myt⸡ deme vadere vnde myt deme hilge(n)

geste to ewighen tyden Amen

** Verse?
*** Rubric
¶

*** Text
[[blue 2][O]] du leflike juncvrouwe van gode

vp synen hillighen berch syon ge-

stedighet ene konyngynne make vns

denende dy neme sone in vrůchten

vnde ene hoghelouen myt beuynge

** Psalm
*** Rubric
psalmus

*** Text
[[red 3][W]]or v(m)me gry(m)meden

de lude: vnde dat volk de dachten

de ydelheit. [[green][D]]e erdeschen ko-

nynge vnde de vursten quemen to

samen: jegen dan heren vnde tiegen

cristo. [[blue][W]]y breken ere bende: vnde wer-

pen van vns ere / [[red][D]]e dar wonet

an den hemele de schal se bespotten:

vnde vns here schal se besch⸠e⸡⸌y⸍mpen

---4r---

[[green][D]]enne schal he to en spreken in syne(n)

torne: vnde in syme v(m)mode wil he se

bedrouen. [[red][S]]under ik byn eyn konynk

ghesettet van eme vpp synen hilligen

berch syon. to kůndeghen syn bot ~

[[blue][G]]ot sprak to my du bist myn sone:

huten ghebar ik dy. [[red][B]]idde van my

ik gheue dy volk dyne erue: vnde de

ende der werelt stät an dyner walt.

[[green][D]]u scholt se righten an eyner yseren

roden: vnde schalt se to breken also

enen erdenen gropen [[blue][U]]nde nv mer-

ket gy konynge: vnde werdet gheleret

gy de dar ordelen de erden. [[red][D]]enet de(me)

heren myt vruchten: vn(de) vrouwet 

jw vor em myt beuynge. [[blue][G]]ripet de

tucht vppe dat sik de here nicht en tor-

ne: |-vn(de)_vorwe-| uppe dat. dat gy nichte(n)

vorgän van deme rechten weghe.

[[green][W]]en er syn torne in korten bernet:

salich synt de. de an em louen. [[red][E]]re

sy deme vader 

** Antiphone
*** Rubric
Antiphona.

*** Text
[[blue 2][O]] entfanger vnde ere der junc-

vrouwen. maria sta vp jegen

---4v---

vnse weddersaten. vnde dyne be-

nediginghe kome vppe dyn volk

** Psalm
*** Rubric
psalmus

*** Text
[[red 2][H]]Ere wor v(m)me

synt ghemeret de jene(n) de my

bedrouen: der is vele de my tiege(n)

stan [[blue][U]]ele de seden dat in myner

selen were neyn heyle synes godes.

[[red][S]]under du here entfangest my:

du bist myn ere vnde vorhogest my(n)

houet. [[green][J]]k rep to gode myt myner 

stempne. vnde he twide my van

synen hilligen berge. [[red][I]]k slep vn(de)

rouwede vnde stunt vp wente got 

entfingh my. Jk schal nicht vru-

chten dusent volkes dat se my be-

gripen: here got staa vpp vn(de) make

my salich myn got. [[red][W]]ente du hest 

gheslaghen alle myne wedder sate(n)

my sunder sake: de tenen der sunder

hestu to broken [[green][U]]nses heren is

dat heil vnde vp dyne volk kome

dyn benediginghe. [[red][E]]re sy deme

vader vnde deme sone vn(de) deme hil-

lighen gheste. Alse i{s/t} was (et_cetera)
