#+TITLE: 

|------------+-------------|
| Manuscript | AM 70 8vo   |
| Locus      | 64r:1 65r   |
| Work       | PSALM_16    |
| Language   | gml         |
| Status     | transcribed |
|------------+-------------|

* Transcription
[[red 2][H]]Ere twide my(n) rechtuerdic-

heit, gedenk an myne gebet

[[red][M]]it dine(n) oren wnfange my(n) bet,

nicht myt valschen lippen [[red][U]]an

dyneme antlat wtgeyt my(n) ordel,

dyneme oghen seen licheit [[red][D]]u 

hefst my(n) herte geprowert. vnde

sochte in der nacht. du vorsuchte-

de my in den uwr, vn(de) neen bøs-

heit is uwnden in my [[red][D]]at myn

mu(n)t nicht en spreke mynschen 

werke. dor dyne lippes worde. hebbe

ik behudet harde weghe [[red][U]]wlbri(n)g

mynen gank in dyneme stighe,

dat myne votstappen nicht bewe-

get werden [[red][I]]k rep wente du got

gehordest my, neghe din oren my

vnde twide myne worde [[red][U]]wnder-

lich make dyn barmherticheit,

du dar gesund makest dene der

---64v---

hope an dy [[red][B]]ehude my vor de-

ne der diner vorder hant tegen

stan, also deme ogen steen [[red][B]]e-

skerme my vnder skeme dyne 

vlogeles, van deme wmildes ant-

lat der my piniget [[red][M]]iner viende

v(m)meringet myner sele vn(de) vmbe-

sloten siner vitten, er munt sprak

hokuert [[red][D]]e my wtskuwede heb-

ben my v(m)Mmeringet, er oghene

skickeden se negeden to deme erde

[[red][S]]e toghen my also en lowen de

bereyde is to sin roff, vnde also 

en lowe welp de d\a/⸠e⸡r wonet in

der kulæ [[red][H]]ere sta vp vnde kom

vor em, vnde drok em neder,

vrij myne sele van der wmilde.

vnde nem \dat/ swerd dynes hendes

van dyneme viende [[red][H]]ere skey-

de see van cleyne mynsche va(n)

---65r---

der erde in ere lewe(n)t, er liiff is

bwl van dyneme bedeckede dinge

[[red][S]]ee sint sat van kindere, vnde se

naleten sine iu(n)gelinge syneme

godere [[red][U]]nde ik skal obenbares

in rechuerdicheit in dyner an-

sicht, vnde schal sat werden wen

dyneme ere sith openbaret [[red][E]]re
