#+TITLE: Credo

|------------+-------------|
| Manuscript | AM 738vo    |
| Locus      | 136v 137r   |
| Work       | Credo       |
| Language   | Low German  |
| Status     | transcribed |
|------------+-------------|

** Parallels

|------------+----------------------------|
| Danish     | MDB 972, AM 76 8to 41r ff. |
| Low German |  Brandis(?) 1483:109r      |
| Latin      |                            |
|------------+----------------------------|

* Transcription
[[J]]k loue in got vader alwel-

dich. en schepper des hem-

mels vn(n)d der erden. vn(n)d 

in ih(esu)m (christu)m synen en ge-

boren sone vnsen heren.

De dar ys vntfanghen 

van deme hilgen gheiste

geboren van der reynen

iu(n)curouwen marien De

ghepyneghet vn(n)d ghec(r)u-

cighet wart De vnder

poncio pylato to deme

dode. vn(n)d wart begraue(n)

vn(n)d wart neder to der hel-

le. To deme drudden da-

---137r---

ghe stunt he up van dode

vn(n)d vuer vp to hemmele

vn(n)d he syt to der rechtere(n)

hant got vaders alwel-

dich. vn(n)d dar na ys he

to comende richtende o-

uer de leuendighen vn(n)d 

ouer de doden Jk loue in

den hilgen gheist in de 

hilgen kerken der criste(n)-

heit Jn de menscap der

hilgen Jn vorlatunge der

sunde vn(n)d in vpstandin-

ghe des vlesches. vn(n)d in

dat ewighe leuent. Ame(n).
