#+TITLE: St. Augustine
|------------+-------------|
| Manuscript | Arndes 1487 |
| Locus      | 265r-267r   |
| Language   | Low German  |
|------------+-------------|

** Parallels
|------------+------------------|
| Latin      |                  |
| Low German |                  |
| Danish     | MDB 801, MDB 808 |
|------------+------------------|

* Transcription
** Rubric 
¶ Uan sunte Augustino
** Text
O du eddel byscop van
ypoen sunte augustyn
eddel nach der boerd
men altouele meer eddel in de-
me crystene louen, vnde dyner
duerbaren lere. du weerde aerne
---265v---
bouen allen doctoren. du bist bo-
uen mate ghevloghen in de ho-
ghe. myt deme hillighen ewange-
listen sunte iohanne. mynschen her-
te kan dyne hoghen lere kume
begripen. dyne weerde moder
monica. heft blodyghe trane vor
dy ghoten. eer du wordest beke-
ret vnde ghedoft. van sunte ambro-
sio deme weerden biscoppe van
meylaen. vnde god heft ze gnedi-
ghen wol ghetweden. als du ho-
redest dat hillighe leuend sunte
anthonij des leygen. do ghote-
stu dine vylbitteren trane vnde spre-
kest Ach wat pine is dit. de vn-
ghelereden vorrisen. vnde winnen den
hemmel. myt macht vnde mit wald.
---266r---
wy ghelereden werden vorsenket
in de helle myt vnsenr kunst Al-
len ketteren bistu eyn swaer ha
mer ghewesen. wath du nicht
gheweten heffst. des mach eyn
cristen wol vnwenten zyn O du
clare vleet des paradyses. de
stenyghen herte bewekestu myt
dyner lere. De warlnd vnde al
le ere ghued vnde lust hefstu
als nicht gheachtet. dusent vnde
druchtich boke hefstu gheseth.
dat neen man zo vlytich mach
zin. dat he ze alle ouer leze Alle
achtersprake hefstu ghehatet vnde
vorboden alzo slanghen venyn. gro
te spenghinghe. vnde aller vrouwen
---266v---
afwesent hefstu beleuet. wente vn
tuchtigher vrouwen leue men-
nighen man bedreghet. de bozen
gheyste weken vor dyner hand
van den beseten, wen du ze rore
dest altohand. do du bedest vm-
me de doed. do twidede di god
vnde halp dy vth aller noed. dy-
ne reyne zele quan to male claer.
alto hant yn der enghel scaer.
als du haddest gheleuet sos vnde
de souentych iaer. Nu rouwet
dyn hillyghe beente al vorwaer.
Do pauie. grote mirakel. deyt
god al daer. dorch dn vordeenst
vnde dyn ghebed. dede gode tru
wet. he ene numer vorlet. Ach
hilghe vader sprik vor vns ein
---267r---
gnedich woerd. wente god heft
dy vakene myt gnaden hoerd,
** Rubric 
¶ Dat versikel
** Text
Sich wylk eyn grot prester. de
de gode in synen daghen heft be
haghet. vnde ys ghaer recht ghe
vnden.
** Rubric
¶ De Collecta.
** Text
Almechtighe god. sta io bi
knsen ynnighen bede. vnd
le du vorlenest. dat to vorsicht
dyner vorhopene myldicheyt.
de ghif gnedich dorch dat bed
dynes hillighen bychtighers vnde
biscoppes sunte augustini dy-
ner woenliken barmherticheyt
ghaue. dorch vnsen leuen heren
ihesum cristum Amen
