#+TITLE: Transcription of Prayers in Org-Mode

* Metadata
The metadata for the file starts from the very beginning with the ~#+TITLE:~. Here the human-readable verison of the title is given, e.g. ~Hours of the Virgin (matins)~. This will be converted in TEI to the ~<titleStmt>~.

What follows is a table with the other metadata which will be placed inside the ~<fileDesc>~.

|------------+---|
| Manuscript |   |
| Locus      |   |
| Work       |   |
| Language   |   |
| Status     |   |
|------------+---|

- Manuscript :: Provide the key for the manuscript, e.g. ~AM08-0073~ for AM 73 8vo.
- Locus :: Provide the first and final page separated by a space, e.g. ~9r 9v~
- Work :: Provide the key for the work (if available), e.g. ~HOURS_VIRGIN.matins~ for Hours of the Virgin (matins)
- Language :: Provide the three-letter key for the language: /dan/ (Danish), /gml/ (Middle Low German), /lat/ (Latin)
- Status :: Indicate the status of the transcription. Options include /started/, /transcribed/, /proofread/ etc.


* Transcription
The beginning of the transcription is marked with a top-level headline ~* Transcription~. This will mark the beginning of the ~<body>~ in TEI. 

** Text structure
Org-mode headings (indicated with asterisks) will produce nesting ~<div>~ tags in TEI.

The three most prominent div types are:

- Text :: The main text.
- Rubric :: Any text in red either at the beginning or end of a main text.                   
- Incipit :: Latin incipits for texts in the vernacular. These are often underlined in the manuscript.

In addition, a given text might have one of the following structural elements (especially at the end) in which the above elements can be nested:
- Versicle :: 
- Respond ::
- Antiphon ::
- Lesson ::
- Chapter ::


# What about the orders for the Gloria Patri, etc?

** Mise-en-page
The following macros will be used to indicate the most salient features of the mise-en-page (layout) of the manuscript.

*** Lines and pages
A double hard return is used to indicate a new line, which will result in a ~<lb/>~ tag in the TEI. New pages are indicated with the folio number inside a triple-hyphen.

For example, the org-mode transcription:
#+BEGIN_SRC org
zele vnde make my salich dor

dine barmherticheit Wente

---13v---

nement de is in deme dode: de

dyner dechtik sin vnde we louet
#+END_SRC 

Results in:

#+BEGIN_SRC xml
<lb/> zele vnde make my salich dor
<lb/> dine barmherticheit Wente
<pb n="13v"/>
<lb/>nement de is in deme dode: de
<lb/>dyner dechtik sin vnde we louet
#+END_SRC

Note that a rubric or main text does not always begin on a new line, but instead begins in-line. When a new structural text element (text, rubric, incipit etc.) begins on a new line, use a double hard return after the element header:

#+BEGIN_SRC org
** Rubric

Hijr begint
#+END_SRC

results in:

#+BEGIN_SRC xml
  <div type="rubric">
  <lb/>Hijr begint
#+END_SRC 
*** Enlarged and colored initials
Initial hierarchy can be important in distinguishing parts of a text. Enlarged and colored initials are placed inside a double-bracket ~[ [ ] ]~ which will automatically result in an underlined link in the org-file. These will be converted to ~<hi>~ tags in TEI.

It can be useful to include information about the color and height of initials. These can be done inside the first set of brackets with the number and color(s) separated by a whitespace. For example a three-line initial /M/ which is in red and blue (puzzle initial) can be indicated by encoding ~[[3 red blue][M~. In-line (single height) initials can be indicated simply by color, e.g. ~[[green][W~.

*** Editorial interventions
**** Expansion of abbreviations
Abbreviation markers are not indicated in the transcription. Instead, abbreviations are expanded using parentheses ~( )~ which will be converted to ~<ex>~ tags in TEI. Note the following common abbreviations and their expansions:

- ~m(eth)~ is expanded following the convention in MDB
- ~vn(de)~  

**** Blank spaces in words
Spaces inside of a word are transcribed with an underscore ~_~

**** SIC/CORR
Clear mistakes in the text are indicated in curly braces separated by a foreward slash: {sic/corr}. For example:

#+BEGIN_SRC org
  Ere sy {m/d}eme vadere
#+END_SRC

Results in:

#+BEGIN_SRC xml
Ere sy <choice><sic>m</sic><corr>d</corr></choice>eme vadere
#+END_SRC

**** Names
Personal names are tagged using double angled brackets ~<< >>~ and an optional key. the key is given first in CAPITALS followed by a forward slash: ~<<KEY/name>>~. Note the double angled brackets will result in an underline in the org file.
