#+TITLE: A Prayer for Every Day in Lent

|------------+--------------------------|
| Manuscript | Speghel der Sammiticheyt |
| Locus      | R1r R3v                  |
| Work       | LENT_DAILY               |
| Language   | gml                      |
| Status     | Transcribed              |
|------------+--------------------------|

* Transcription
** Rubric
¶ Eyn bed. de ghantzen vaste(n)

ouer. alle daghe

** Text

[[red 4][L]]Eue here. vth der

grote(n) dupe. myner

sware(n) sunde. rope

ik vorloren sone. to

di vader, aller gnade vn(de) barm-

herticheyt. de du nemande vor-

lust vn(de) vorsmaest. sunder he wil-

le vorloren vn(de) vorsmaet wesen.

dar vmme seette yk alle mynen

troest an di. vnde spreke. Criste

des leuendyghen ghodes sone.

vorbarme dy myner. wente yd

is dy eechlyk vn(de) natuerlik. dat

du alle tijd schonest den armen

sunderen. dede wedder to di ke-

---261---

ren wylle(n). Jk bin alte verne va(n)

dy vorduelet. vn(de) ka(n) doch nycht

wedder komen to dy. su(n)der du

helpest my. Jk wolde gheerne.

me(n) dat vulle(n)bringhent is nicht

by my. Myner su(n)de is neyn en-

de. in da(n)ken. in worde(n). i(n) werke(n).

in quader woenheyt. in ri(n)gwe-

ghinghe. vn(de) in entschuldynghe

myner sware(n) sunde. Almechti-

ghe god. ik hebbe dy nicht vor-

oghe(n) gheholde(n). als myne(n) here(n)

vn(de) god. minen salichmaker vn(de)

vorlozer. Mine(n) neghesten heb-

be yk vorerghert. vn(de) to sunden

ghebracht. Wat eghe ik arme.

dorre. afghesnede(n) rijs. va(n) di wa-

re winstokke. me(n) dat du na dy-

---262---

ner rechtuerdycheyt. my weer-

pest in dath ewyghe vur. Ach

wol ghift nu myneme steinighe(n)

herte(n) ware ruwe. myne(n) oghen

de(n) borne der trane. dat ik slym-

me moerder myner armen zele

nacht vn(de) dach. beweyne(n) vn(de) be-

scryen moghe: den doed miner

zele. vn(de) eer afschedent va(n) gode

myneme heyle. O here vn(de) va-

der. ghyf my de(n) borne der gna-

de. de(n) du in der wustenye. dyne-

me volke gheuest dat vorquik-

kende water. vth deme harden

steine. Ghif mi de traen marie

magdalene(n) des speghels der su(n)-

dere. su(n)te peters di(n)es vorsekers

Hore myt gnade(n) my arme sun-

---263---

dere. de ik doch vake(n). dy nicht

horen wolde. Gheystu in dath

scarpe richte. myt dyneme ar-

men knechte. zo byn ik vorlore(n).

wente neen mynsche wert vulle(n)

komen richtich, vor di ghev{n/u}n-

den. Reynighe min herte. ik o-

pene dy dat openbaer. du allei-

ne ke(n)nest mi. Gnade de ik nicht

en heebbe ghyff my. vp dat yk

in dyssen daghen der gnade vn-

de der penite(n)cien. Moghe my

myt dynen gnaden, beheghelik

maken. dat ik ghereinighet van

alle mine(n) sunden. dy ware paes-

chelam. entfanghen moghe. yn

myn heerte vn(de) in myne zele. vp

dat ik ghanslyken in dy vmme-

---264---

ghebyldet werde. dat ik dy le-

ue, vnde nicht my. alzo dath ik

ewych blyue by dy. des heelp

mi. du weerde god. vader. sone.

vn(de) hillighe gheyst. du hyllighe

dreuoldicheyt in dren personen

vn(de) in eyneme wesende Amen

** Versicle
*** Rubric

¶ Dat versikel

*** Text

Here. do vns nycht na vnsen

sunden. vn(de) betale vns nicht na

vnsen vnlyken boeszheyden

** Collect
*** Rubric

¶ De collecta

*** Text

[[2 blue][A]]lmechtighe ewighe god.

dorch de ere dynes na-

men wylle vns nicht vorlezen, 

vmme vnser vele(n) myssedaed. me(n)

dorch. dat stede vorbydde(n)t der

iuncfrouwe(n) marie(n) der ewyghe(n)

---265---

reynen iuncfrouwen. vn(de) dorch

de bede. vn(de) dat grote vordee(n)st

alle dyner vterkoren. vorleene

vns dine gnade. vn(de) de tijd der

waren penitencien. dat wy ghe-

vryget va(n) alle vnsen benden in

reyner co(n)sciencie(n) va(n) dy weerde(n)

gnedighe(n) entfa(n)ghe(n). in dat ewy-

ghe leuend aller vroude Ame(n).

*** Rubric

¶ Dyt bed machstu alle tijd

vor dyne sunde lesen
