#+TITLE: A prayer of confession

|------------+-------------|
| Manuscript | C 496       |
| Locus      | 1r:1 1v     |
| Work       |             |
| Language   | gml         |
| Status     | transcribed |
|------------+-------------|

* Transcription
** Text
sere in den sunden byn liggende O

ihesu criste dy hebbe ik allene gesun-

diget dy bichte ik dat ik seer hebbe

gesundiget Jegen dy vn(de) alle dyne en-

gele Jn worden. Jn werken in besmyt-

tinge myner sele vn(de) licha(m)mes vn(de) myt

velen quaden danken O ik vnselige 

my(n)sche. bekenne dat myne sunde synt

vntellik. O alweldige god vorbarme

dy myner wente ik hebbe vorgiffe-

nisse van dy vn(de) van dynen engelen

vn(de) van alle dynen hilgen vor alle my-

ne sunde de ik ie werlde gedan hebbe

O here wes gnedich my sunderynne(n).

Wente alle myne sunde synt my gans

sere leyt. De ik ie werlde gedan heb-

be Jegen dynen gotliken willen O he-

re giff my de gnade. Jn desseme leuen-

de to donde warafftige bote. dar dorch

mogen vth gedan werden alle myne

sunde. wente ik weit nicht to weme

dat ik schal hebben to vlucht sunder

allene to dy ih(esu)m (christu)m de du bist dat

---1v---

leuent der leuendigen. Vnde de vpstan-

dinge der doden Bidde vor my O

du alder hilligeste ioncfrouwe maria

Biddet vor my alle hilligen engele

Erdesche engele. Trom. Dominacio-

nes. principatus. vn(de) potestates. vir-

tutes cherubin vn(de) seraphin. Biddet

vor my alle gy patriarchen vn(de) pro-

pheten. Biddet vor my alle gy ap-

postelen vn(de) ewangelisten. Biddet 

vor my alle gy mertelere vn(de) bich-

tegere. Biddet vor my alle gy ionc-

frouwen vn(de) wedewen. Biddet vor

my alle gy vterkaren vn(de) hilgen dat

de alweldige god vppe my vorluchte

syn hilge angesichte vn(de) sik vorbarme

auer my armen sunderynne(n) Amen
