#+TITLE: A prayer to God Christ Mary and the Saints

|------------+-------------|
| Manuscript | C 496       |
| Locus      | 2r:6 3r     |
| Work       |             |
| Language   | gml         |
| Status     | transcribed |
|------------+-------------|

* Transcription
** Text
[[red 2][O]] Alweldige ewige gnedige god.

De du bist eyn herscopper der le-

uendigen vn(de) der doden. De du beken-

nest alle de dyn synt Jn deme louen

vn(de) in den werken. Jk arme sundery(n)-

ne bidde dy otmogen. dattu dorch

dyne groten milden barmherticheit.

O gude ih(es)u (christ)e wyllest vplosen de

bende alle myner sunde vn(de) aller my(n)-

schen Vn(de) dorch dat bet der alder hil-

ligesten Joncfrouwen Marien dyner

leuen moder. Vn(de) alle dyner hilgen. Wil-

lest vnsen heren den pauwes. Bisscoppe

Cardinale. Alle prelaten dyner hilgen

kerken. Vn(de) alle vorsamelinge en be-

uolen. Ok alle geistlike mo(n)nike. bro-

dere. edder closter ioncfrouwen konin-

ge hertogen vn(de) alle cristene fursten.

---2v---

Ok alle cristene mynschen vn(de) my dyne

armen denerynnen vn(de) alle de dy to

denste synt bewaren in aller hillicheit

vn(de) geistlicheit by sunderen O leue here

ih(es)u (christ)e. de my synt to gedan van blo-

des wegen. edder ander vruntschop. Van

denstaffticheit wegen Edder gebedes wil-

lest reynigen van allen sunden Vorluch-

tegen myt den dogeden Vn(de) geuen en den

vrede vn(de) de ewigen salicheit. Vordriff

ok van vns leue here alle vnse sicht-

like vn(de) vnsichtlike viande. Dode in vns

alle vleischlike begeringe. Giff vns

een bequeme gud wedder Vormere vn(de) 

benedye de vruchte der erde vn(de) giff

my vn(de) alle mynen vianden de waraff-

tigen leue Giff ok allen guden pelegry-

men. enen seligen luckigen wech Allen

vnsen kranken suntheit. Vn(de) allen loui-

gen. se synt leuendich edder doet. de 

vroude des ewigen leuendes O du sa-

lichmaker der werlt Jh(es)u (christ)e de du

leuest vn(de) regnerest myt dem vadere

---3r---

vn(de) myt dem hilgen geiste vw vn(de) to

ewigen tyden Amen
