#+TITLE: Adoro Te

|------------+-----------|
| Manuscript | C 496     |
| Locus      | 9r6 10r   |
| Work       | ADORO_TE  |
| Language   | gml       |
| Status     | proofread |
|------------+-----------|

* Transcription
** Text
[[red 2][O]] Here ih(es)u (christ)e ik bede dy an also

du heuest gahangen an deme hilge(n)

cruce. Vn(de) gehat vppe dyneme houede 

de dornen cronen ik biddy dy. dat dyn

cruce my lose van deme slanden engele

Ame(n)

** Rubric
p(ate)r n(oste)r

** Text
[[red 2][O]] Here ih(es)u (christ)e ik anbede

dy also du vorwundet bist an dem

cruce vn(de) gedrenket myt etike vn(de) myt

gallen Jk bidde dy dat dyne wunden

syn ene arstedye myner sele Amen

** Rubric
p(ate)r n(oste)r

** Text

[[red 2][O]] Here ih(es)u (christ)e ik bede dy an also

du begrauen bist vn(de) myt mirre(n)

vn(de) myt durbaren kruden gasaluet Jk

bidde dy dat dyn doet sy myn leuent

Amen

** Rubric
pater noster

** Text
[[red][O]] Here ih(es)u (christ)e ik

bede dy an also du dale stegest to der

helle vn(de) de vangene vorloset heuest

Jk bidde dy lat my dar nicht in gan Ame(n)

---9v---

[[red][O]] Here ih(es)u (christ)e ik bede dy an. also du

bist vp gestan van deme dode. Vpgeste-

gen do den he(m)melen. vn(de) sittest to der vor-

deren hant dynes vaders. Jk bidde dy

vorbarme dy ouer my Amen

** Rubric
pater n(ost)er

** Text

[[red][O]] Here ih(es)u (christ)e du gude herde. beholt

de rechtuerdigen make rechtuerdich de

sundere vorbarme dy ouer alle louigen

mynschen. Vn(de) wes gnedich my arme(n) sun-

dere Amen

** Rubric
pater noster

** Text
[[red][O]] Here ih(es)u (christ)e

dorch de bitterheit. de du ledest vor my

in dem cruce alder meist. also dyne alder

eddelste sele scheidede van dyneme licha(m)me

vorbarme dy myner sels Jn ereme affsche-

dende Amen

** Rubric
pater noster aue maria

** Rubric
Collecta

** Text

[[red 2][O]] alderleueste here he(m)melsche vader Jk

offere dy den vnschuldige(n) doet. dynes

leuen sones. Vn(de) de leue synes gotli-

ken herten. Vor alle pyne vnde

schult de ik arme sunder vor my-

ne sunde vordenet hebbe. Vor alle 

myne leuen vrunde leuendich vn(de)

doet. Vor alle dyne vterkorne vn(de)

---10r---

vor alle sundere ik bidde dy vorbar-

me dy ouer vns Amen

** Rubric
p(ate)r noster

** Rubrice

Jd is to wetende dat eyn Jewelik Jnnich

boetwerdich my(n)sche dede heft gebichtet

vn(de) deme syne sunde leet synt vn(de) gebich-

tet heft vn(de) bedet desse vorscreuen soue(n)

bede myt soue(n) pater noster vn(de) souen

aue maria de vordenet van dem pauwese

<<GREGORY/gregorio>> vn(de) van anderen pauwesen xl du-

sent xlviij iar vn(de) xxvi dage afflates.
