#+TITLE: Acrostic poem
| Manuscript | UUB H 122 |
| Locus | 95r-96v |
| Language | Low German |

* Transcription
[[A]] Am beghin byn ik ghenant. in allæn dingæn

byn ik bekant. Se mynæ godæ nicht

to forre an. Er dw wornemest de ændæ darwæn.

[[B]] beydent is tomalæ goth. haftigheyt dykkæ 

stadæn dot. se wo sich de ændæ heret. so

warstu wan deme ambegine ghe eræt

[[C]] Claghe is der art. De sich wol vør bewort

de is klok van synne. van dem ænde wente 

iin dat ambeghin(n)e

[[D]] De dar steyt an warheyt. allæn dat de

wilæ geyt. De wisæt dy dat wt beydæn

stillæ vnde owærlut

[[E]] Ere is also getan. De dat vnere kan laen.

De is wisær van salamon. vndæ stærkær

wen samson

--95v--

[[F]] Fyn schon vn(de) dar by stolt. kust men

dykkæ bowen gholt. de dar fyn is vn(de) 

dar by ghut. got va(n) he(m)mel he sulwæn doot.

[[G]] Gnade gheyt bowen recht. also vns

de scrift vt lecht. scholde got na sunden 

richtæn. So moste seel vn(de) liif vornichten.

[[H]] Homuth wol seggen sor. ere my ik \vn(de9)/ ere

dy dat is wor. wltu my vorwerwen.

ik wil dy wedder vorderwen

[[I]] Innicheyt is der selen en raat. de heft

an sich de hemmel schaat de dar innich

is an desser tydh. den maket got wese sey des

[[K]] Kundicheyt vn(de) klokheyt. de steyt ¶qwith.

to prisende we se treyt. deme kundichen

heft got dat gut. Dæn kloken. got sich sulwen

[[L]] Lef van allæn luden. sperek ¶ leuet.

van nemende arich. dat rade ik. loff dat

is en kloker sede. deystu dat. so louæt dy

[[M]] Mennech man is vor ¶ got sulwen.

--96r--

oldet. in godes denste. vor koldet. do de iung

en iaren weren dyn do weldestu. alle tiid ower

[[n]] Nierne schal nicht wesen dyn. ¶ vlede syn.

mut. alto nyerne is incht gut. wor du vyn-

nest trw an. den scholtu lefliken vnt fan

[[O]] Ormat steyt to prisen io. an erde syde an

hemmel ho. lestu dy dat betyden an. soo

lowet dy beyde vrowen vnde man

[[P]] Pinse vn(de) prøwe an dingemote. wor du

kerest dynes -her- hertsen ghote. setu dat

tu dy so ghesellest. datu dar na dat nicht ant

[[Q]] Qwite vns got van leyde. dy ¶ghellest

vn(de) my vns beyden. vn(de) alle bedderwe

lude vort de dar døghet vn(de) ere begheret

[[R]] Reynicheyt vn(de) rechtferdicheyt. de steyt to

prisende. we se -d-treyt. kusk reyne an dyn

hertse rechtferdicheyt. gheyt bowen alle ærtse

[[S]] Stete hertse vn(de) stylle mot. des love ik

mer wen dusent punt. ves stete vnde 

--- 96v ---

wndesstyllæ mede so sent dy got sin eweghe

[[T]] Thuchte vns got an vnseme luke ¶ vrede.

roke vns ok an vnseme vnlucke. wppe

dat wi swewen møghen. An desser werlt dat

sel vnde liif nicht werde -misk- misghe stalt

[[U]] Vrude vnde vrome dikke keret. dat

men got nicht en eret. got ghere vrw-

de vnde vrome dat wi nu(m)mer van em kome.

[[I]] Ik qwam mik in deme holte to gan dar

so vant ik eynæ rosen stan. de rose de

vas nicht al rot lef dor dynen willen so

lyde ik nod