* Dit is en innich beth alle tyd to lesende deme mynschen.
Leve Here, ut der groten dupe mynerr sunde rope ick vorlarene dochtere tho dy, vader vul aller gnade unde bermeherticheit, de du nemende vorlust unde vorsmadest, sunder he wil vorsmat unde vorloren wesen. Dar umme sette ick alle mynen trost an dy unde spreke: Criste, des levendighen Ghades sone, vorberme di myner! Wente id is dy echlick unde naturlick dat du alle tyd schonest den armen sundern dede wedder tho dy keren willen. Jck byn alto verne van dy vordwelet unde kan doch nicht wedder komen tho dy, sunder du helpest my. Ick wolde gherne, men dat vullenbringhent is nicht by my. Myner sunde der en is neen ende in dancken, in worden, in werken, in qwader wonheit, in ryngheweghynghe unde entschuldinghe myner swaren sunde. Allemechtige Ghod, ik hebbe dy nicht vor oghen geholden als mynen Heren unde God, mynen salichmaker unde vorlosere. Mynen neghesten hebbe ick dicke vor argerd unde to sunden gebracht. Wat ege ick arme dorre affghesneden rijs van dy, ware wynstock, men dattu na dyner rechtverdicheit my werpest in dat ewige vur? Och wol ghift myneme steynegen herten nu ware ruwe, mynen ogen den borne der tranen, dat ick slymme mordersche myner armen selen nacht unde dach beweynen unde beschrighen moge den doet mynere sele unde ere affschedent van Gade, myneme heyle? O Here unde vaderr, ghiff vorqwickende water ut deme harden steyne! Giff my tranen, so du gevest Marien Magdalenen, de dar is en spegel der sunderrynnen, unde Sunte Peter dinem vorsaker! Hore myt ghnaden my armen sunderynnen, de ick doch vaken dy nicht horen wolde! Geistu in dat scharpe richte myd dynere maget, so bin ick vorlaren; wente neen mynsche wert vullenkomen richtich vor dy gevunden. Reyneghe myn herte! Ick open dy dat apenbar, du alleyne kennest my. Gnade de ick nicht en hebbe, giff my, uppe dat ick in dessen dagen der gnade unde der penitencyen moge my myt dinen gnaden behecklick maken, dat ik ghereyneget mothe werden van allemynen bosheiden unde sunden, so dat ick dy, ware paschelam, mote entfanghen in myne sele unde in myn herte myt ghantsere innicheit, uppe dat ick ganslicken in dy umme gebildet werde, dat ik dy leve unde nicht my unde dat ick tho ewighen tiden myd dy blyve unde nummer van dy scheiden! Des help my, du werdige Ghod, vader, sone unde hillige geist, du werdighe hillige drevaldicheit in dren personen unde in eyneme wesende! Amen
** versiculus.
Here, do uns nicht na unsen sunden unde betale uns nicht na unsen unlicken bosheyden!
** Collecta.
O allemechtige ewige Ghod, dorch de ere dines hillighen benedieden namen wil uns nicht vorlesen ume unser ghroten mysdaet willen! Dorch dat stede vorbiddent der juncfrouwen Marien, der ewigen ryenen junncfrouwen, unde dorch de bede unde dat ghroete vordenst alle dynerr uterrkoren vorlene uns dine gnade unde de tid der waraftigen penytencien, dat wy ghevrighet moten werden van al unsen benden, in reynen consiencien van dy werden ghnedighen entfangen in dat ewighe levent aller vrouden! Amen.
