#+TITLE: XML Catalogue files

Catalogue files follow the TEI P5 guidelines for manuscript description (see tei-c.org)

* Identifier (msIdentifier)
This section provides the identity markers for the location and registration number (shelfmark) of the physical object. It contains three elements: ~<settlement> <repository> <idno>~

~<settlement>~ refers to the city, which is given in shorthand as a three-letter @key.

#+CAPTION: Three-letter keys for cities with manuscript archives for the project.
|-----|------------|
| Key | City       |
|-----|------------|
| KBH | Copenhagen |
| STH | Stockholm  |
| LND | Lund       |
| LIN | Linköping  |
| ROS | Roskilde   |
| KAL | Kalmar     |
| UPS | Uppsala    |
|-----|------------|

~<repository>~ refers to the actual archive, which again is given in shorthand as a three-letter @key.

#+CAPTION: Three-letter keys for repositories (archives) in the project.
|-----|----------------------------|---------------------------------|
| Key | Repository (English)       | Repository (Original lang)      |
|-----|----------------------------|---------------------------------|
| AMS | Arnamagnæan Collection     | Den Arnamagnæanske Samling      |
| KBK | Royal Danish Library       | Det Kgl. Bibliotek              |     
| KBS | National Library of Sweden | Kungliga Biblioteket            |
| KBB | Karen Brahe Library        | Karen Brahes Bibliotek          |
| KSB | Kalmar City Library        | Kalmars Stadsbibliotek          |
| LSB | Linköping City Library     | Linköpings Stadsbibliotek       |
| LUB | Lund University Library    | Lunds Universitetsbiblioteket   |
| UUB | Uppsala University Library | Uppsala Universitetsbiblioteket |
|-----|----------------------------|---------------------------------|

~<idno>~ refers to the shelfmark (call number) of the individual item. It is given both as an @xml:id and as text. The @xml:id roughly follows the pattern REP(size)-0000 though differs per repository due to different registration practices. For example:

#+BEGIN_source
<idno xml:id="AM08-0073">AM 73 8vo</idno> <!-- Copenhagen, Arnamangæan Collection, AM 73 8vo -->
<idno xml:id="UUB-C-0496">C 496</idno> <!-- Uppsala, University Library, C 496 -->
<idno xml:id="GKS04-1615">GKS 1615 4to</idno> <!-- Copenhagen, Royal Danish Library, GKS 1615 4to -->
#+END_source
