#+TITLE: XML Catalogue files

Catalogue files follow the TEI P5 guidelines for manuscript description (see tei-c.org). The root element of each file is ~<TEI xmlns="http://tei-c.org/ns/1.0">~. For the purposes of this project, the file ID (equal to the filename without the filetype extension) will be placed as an @xml:id attribute in the root element, as well as the file type (manuscript, text, work) as an attribute @type. Thus:

#+BEGIN_src xml
<TEI xmlns="http://tei-c.org/ns/1.0" xml:id="AM08-0073" type="manuscript">
#+END_src


The root element ~<TEI>~ requires at least two children. All catalogue information is included inside the child element ~<teiHeader>~. The second child element ~<facsimile>~ contains a single, empty child element ~<surface/>~ to allow for a TEI compliant file.

~<teiHeader>~ contains a single child element ~<fileDesc>~ which contains three parts: ~<titleStmt> <publicationStmt> <sourceDesc>~. The first two parts are roughly the same for each file, though with a unique shelfmark within the ~<title>~ element of the ~<titleStmt>~ element:

#+BEGIN_SRC xml
<titleStmt>
  <title><!-- Shelfmark goes here --></title>
  <respStmt xml:id="SDV">
    <resp when="2024">Cataloguer</resp>
    <persName>Seán D. Vrieland</persName>
  </respStmt>
</titleStmt>
<publicationStmt>
  <authority>When Danes Prayed in German</authority>
</publicationStmt>
#+END_SRC

- Note :: The publication statement may be expanded to provide the ability to cite, perhaps in conjunction with the responsibility statement under the title statement.

~<sourceDesc>~ contains only one child element ~<msDesc>~ which contains the following X parts:

- [[#identifier-msidentifier][Identifier (msIdentifier)]]
- [[#header-head][Header (head)]]
- [[#text-contents-mscontents][Text contents (msContents)]]
- [[#physical-descriptin-physdesc][Physical description (physDesc)]]
- [[#history-and-provenance-history][History and provenance (history)]]

* Identifier (msIdentifier)
This section provides the identity markers for the location and registration number (shelfmark) of the physical object. It contains three elements: ~<settlement> <repository> <idno>~

~<settlement>~ refers to the city, which is given in shorthand as a three-letter @key.

#+CAPTION: Three-letter keys for cities with manuscript archives for the project.
|-----|------------|
| Key | City       |
|-----|------------|
| KBH | Copenhagen |
| STH | Stockholm  |
| LND | Lund       |
| LIN | Linköping  |
| ROS | Roskilde   |
| KAL | Kalmar     |
| UPS | Uppsala    |
|-----|------------|

~<repository>~ refers to the actual archive, which again is given in shorthand as a three-letter @key.

#+CAPTION: Three-letter keys for repositories (archives) in the project.
|-----|----------------------------|---------------------------------|
| Key | Repository (English)       | Repository (Original lang)      |
|-----|----------------------------|---------------------------------|
| AMS | Arnamagnæan Collection     | Den Arnamagnæanske Samling      |
| KBK | Royal Danish Library       | Det Kgl. Bibliotek              |     
| KBS | National Library of Sweden | Kungliga Biblioteket            |
| KBB | Karen Brahe Library        | Karen Brahes Bibliotek          |
| KSB | Kalmar City Library        | Kalmars Stadsbibliotek          |
| LSB | Linköping City Library     | Linköpings Stadsbibliotek       |
| LUB | Lund University Library    | Lunds Universitetsbiblioteket   |
| UUB | Uppsala University Library | Uppsala Universitetsbiblioteket |
|-----|----------------------------|---------------------------------|

~<idno>~ refers to the shelfmark (call number) of the individual item. It is given as text. Note that the file ID has already been used as an @xml:id in the root element and is therefore not needed here.

A full ~<msIdentifier>~ for the manuscript Copenhagen, Arnamagnæan Collection, AM 73 4to would be:

#+BEGIN_SRC xml
<msIdentifier>
  <settlement key="KBH"/>
  <repository key="AMS"/>
  <idno>AM 73 8vo</idno>
</msIdentifier>
#+END_SRC

* Header (head)
At the top of each catalogue entry is a short description of the manuscript in prose, describing its general contents, language, date and any significant and obvious features of the manuscript, such as fragmentation, large miniatures, etc. This is placed inside a ~<head>~ element as text.

When a "glamor shot" image of a manuscript is available, it will be linked inside the head in an element ~<figure>~. For example:

#+BEGIN_SRC xml
<head>
  A fifteenth-century book of hours in Low German with multiple full-page miniatures. It contains added prayers in Danish.
  <figure url="../imgs/AM08-0073.jpg"/>
</head>
#+END_SRC

* Text contents (msContents)

* Physical description (physDesc)
* History and provenance (history)
#+NAME: #history
