#+TITLE: XML Catalogue files

Catalogue files follow the TEI P5 guidelines for manuscript description (see tei-c.org). The root element of each file is ~<TEI xmlns="http://tei-c.org/ns/1.0>~ which requires at least two children. All catalogue information is included inside the child element ~<teiHeader>~. The second child element ~<facsimile>~ contains a single, empty child element ~<surface/>~ to allow for a TEI compliant file.

~<teiHeader>~ contains a single child element ~<fileDesc>~ which contains three parts: ~<titleStmt> <publicationStmt> <sourceDesc>~. The first two parts are roughly the same for each file, though with a unique shelfmark within the ~<title>~ element of the ~<titleStmt>~ element:

#+BEGIN_SRC xml
<titleStmt>
  <title><!-- Shelfmark goes here --></title>
  <respStmt xml:id="SDV">
    <resp when="2024">Cataloguer</resp>
    <persName>Seán D. Vrieland</persName>
  </respStmt>
</titleStmt>
<publicationStmt>
  <authority>When Danes Prayed in German</authority>
</publicationStmt>
#+END_SRC

- Note :: The publication statement may be expanded to provide the ability to cite, perhaps in conjunction with the responsibility statement under the title statement.

~<sourceDesc>~ contains only one child element ~<msDesc>~ which contains the following X parts:

- [[Identifier (msIdentifier)]]
- [[Header (head)]]
- [[Text contents (msContents)]]
- [[Physical description (physDesc)]]
- [[History and provenane (history)]]

* Identifier (msIdentifier)
This section provides the identity markers for the location and registration number (shelfmark) of the physical object. It contains three elements: ~<settlement> <repository> <idno>~

~<settlement>~ refers to the city, which is given in shorthand as a three-letter @key.

#+CAPTION: Three-letter keys for cities with manuscript archives for the project.
|-----|------------|
| Key | City       |
|-----|------------|
| KBH | Copenhagen |
| STH | Stockholm  |
| LND | Lund       |
| LIN | Linköping  |
| ROS | Roskilde   |
| KAL | Kalmar     |
| UPS | Uppsala    |
|-----|------------|

~<repository>~ refers to the actual archive, which again is given in shorthand as a three-letter @key.

#+CAPTION: Three-letter keys for repositories (archives) in the project.
|-----|----------------------------|---------------------------------|
| Key | Repository (English)       | Repository (Original lang)      |
|-----|----------------------------|---------------------------------|
| AMS | Arnamagnæan Collection     | Den Arnamagnæanske Samling      |
| KBK | Royal Danish Library       | Det Kgl. Bibliotek              |     
| KBS | National Library of Sweden | Kungliga Biblioteket            |
| KBB | Karen Brahe Library        | Karen Brahes Bibliotek          |
| KSB | Kalmar City Library        | Kalmars Stadsbibliotek          |
| LSB | Linköping City Library     | Linköpings Stadsbibliotek       |
| LUB | Lund University Library    | Lunds Universitetsbiblioteket   |
| UUB | Uppsala University Library | Uppsala Universitetsbiblioteket |
|-----|----------------------------|---------------------------------|

~<idno>~ refers to the shelfmark (call number) of the individual item. It is given both as an @xml:id and as text. The @xml:id roughly follows the pattern REP(size)-0000 though differs per repository due to different registration practices. For example:

#+BEGIN_SRC xml
<idno xml:id="AM08-0073">AM 73 8vo</idno> <!-- Copenhagen, Arnamangæan Collection, AM 73 8vo -->
<idno xml:id="UUB-C-0496">C 496</idno> <!-- Uppsala, University Library, C 496 -->
<idno xml:id="GKS04-1615">GKS 1615 4to</idno> <!-- Copenhagen, Royal Danish Library, GKS 1615 4to -->
#+END_SRC

A full ~<msIdentifier>~ for the manuscript Copenhagen, Arnamagnæan Collection, AM 73 4to would be:

#+BEGIN_SRC xml
<msIdentifier>
  <settlement key="KBH"/>
  <repository key="AMS"/>
  <idno xml:id="AM08-0073">AM 73 8vo</idno>
</msIdentifier>
#+END_SRC

* Header (head)
At the top of each catalogue entry is a short description of the manuscript in prose, describing its general contents, language, date and any significant and obvious features of the manuscript, such as fragmentation, large miniatures, etc. This is placed inside a ~<head>~ element as text.

When a "glamor shot" image of a manuscript is available, it will be linked inside the head in an element ~<figure>~. For example:

#+BEGIN_SRC xml
<head>
  A fifteenth-century book of hours in Low German with multiple full-page miniatures. It contains added prayers in Danish.
  <figure url="../imgs/AM08-0073.jpg"/>
</head>
#+END_SRC

* Text contents (msContents)

* Physical description (physDesc)]]
* History and provenane (history)]]
