#+TITLE: XML Catalogue files

Catalogue files follow the TEI P5 guidelines for manuscript description (see tei-c.org). The root element of each file is ~<TEI xmlns="http://tei-c.org/ns/1.0">~. For the purposes of this project, the file ID (equal to the filename without the filetype extension) will be placed as an @xml:id attribute in the root element, as well as the file type (manuscript, text, work) as an attribute @type. Thus:

#+BEGIN_src xml
<TEI xmlns="http://tei-c.org/ns/1.0" xml:id="AM08-0073" type="manuscript">
#+END_src


The root element ~<TEI>~ requires at least two children. All catalogue information is included inside the child element ~<teiHeader>~. The second child element ~<facsimile>~ contains a single, empty child element ~<surface/>~ to allow for a TEI compliant file.

~<teiHeader>~ contains a single child element ~<fileDesc>~ which contains three parts: ~<titleStmt> <publicationStmt> <sourceDesc>~. The first two parts are roughly the same for each file, though with a unique shelfmark within the ~<title>~ element of the ~<titleStmt>~ element:

#+BEGIN_SRC xml
<titleStmt>
  <title><!-- Shelfmark goes here --></title>
  <respStmt>
    <resp when="2024">Cataloguer</resp>
    <persName key="SDV">Seán D. Vrieland</persName>
  </respStmt>
</titleStmt>
<publicationStmt>
  <authority>When Danes Prayed in German</authority>
</publicationStmt>
#+END_SRC

- Note :: The publication statement may be expanded to provide the ability to cite, perhaps in conjunction with the responsibility statement under the title statement.

~<sourceDesc>~ contains only one child element ~<msDesc>~ which contains the following X parts:

- [[#identifier-msidentifier][Identifier (msIdentifier)]]
- [[#header-head][Header (head)]]
- [[#text-contents-mscontents][Text contents (msContents)]]
- [[#physical-descriptin-physdesc][Physical description (physDesc)]]
- [[#history-and-provenance-history][History and provenance (history)]]

* Identifier (msIdentifier)
This section provides the identity markers for the location and registration number (shelfmark) of the physical object. It contains three elements: ~<settlement> <repository> <idno>~

~<settlement>~ refers to the city, which is given in shorthand as a three-letter @key.

#+CAPTION: Three-letter keys for cities with manuscript archives for the project.
|-----|------------|
| Key | City       |
|-----|------------|
| KBH | Copenhagen |
| STH | Stockholm  |
| LND | Lund       |
| LIN | Linköping  |
| ROS | Roskilde   |
| KAL | Kalmar     |
| UPS | Uppsala    |
|-----|------------|

~<repository>~ refers to the actual archive, which again is given in shorthand as a three-letter @key.

#+CAPTION: Three-letter keys for repositories (archives) in the project.
|-----|----------------------------|---------------------------------|
| Key | Repository (English)       | Repository (Original lang)      |
|-----|----------------------------|---------------------------------|
| AMS | Arnamagnæan Collection     | Den Arnamagnæanske Samling      |
| KBK | Royal Danish Library       | Det Kgl. Bibliotek              |     
| KBS | National Library of Sweden | Kungliga Biblioteket            |
| KBB | Karen Brahe Library        | Karen Brahes Bibliotek          |
| KSB | Kalmar City Library        | Kalmars Stadsbibliotek          |
| LSB | Linköping City Library     | Linköpings Stadsbibliotek       |
| LUB | Lund University Library    | Lunds Universitetsbiblioteket   |
| UUB | Uppsala University Library | Uppsala Universitetsbiblioteket |
|-----|----------------------------|---------------------------------|

~<idno>~ refers to the shelfmark (call number) of the individual item. It is given as text. Note that the file ID has already been used as an @xml:id in the root element and is therefore not needed here.

A full ~<msIdentifier>~ for the manuscript Copenhagen, Arnamagnæan Collection, AM 73 4to would be:

#+BEGIN_SRC xml
<msIdentifier>
  <settlement key="KBH"/>
  <repository key="AMS"/>
  <idno>AM 73 8vo</idno>
</msIdentifier>
#+END_SRC

* Header (head)
At the top of each catalogue entry is a short description of the manuscript in prose, describing its general contents, language, date and any significant and obvious features of the manuscript, such as fragmentation, large miniatures, etc. This is placed inside a ~<head>~ element as text.

When a "glamor shot" image of a manuscript is available, it will be linked inside the head in an element ~<figure>~. For example:

#+BEGIN_SRC xml
<head>
  A fifteenth-century book of hours in Low German with multiple full-page miniatures. It contains added prayers in Danish.
  <figure url="../imgs/AM08-0073.jpg"/>
</head>
#+END_SRC

* Text contents (msContents)
The text contents of a manuscript are grouped in a single element ~<msContents>~. Individual texts are grouped in an element ~<msItem>~, which can be nested.

#+BEGIN_src xml 
<msItem n="15" class="prayer" corresp="AM08-0073_237v">
   <locus from="237v" to="238v"/>
   <title key="MAGNIFICAT">Magnificat</title>
   <textLang mainLang="gml" otherLangs="lat"/>
   <rubric><hi>M</hi>agnificat</rubric>
   <incipit>Myne sele grote den herren</incipit>
   <explicit>vnde lat en shine<ex>n</ex> dyn ewige licht.</explicit>
</msItem>
#+END_src

The element ~<msItem>~ has two required attributes @n and @class. A third attribute @corresp links the text content listed to a text file where the text has been edited.

** Metadata elements
The first few elements inside ~<msItem>~ refer to metadata about the text as found in the manuscript. All are required for every ~<msItem>~.

The element ~<locus>~ gives the start and end of the text as folio numbers (with r/v). When a given text is only found on a single side, the attributes @from and @to have the same value.

The title of the text is given in an element ~<title>~. When the text is a known *work*, the key for that work is given as an attribute @key. Note that this does not necessarily mean a file exists for that work.

The language(s) of the text are given in the element ~<textLang>~ as attributes. A required attribute @mainLang indicates the primary language of the text, while any other languages are given in an optional attribute @otherLangs. Language codes follow the three-letter ISO and are defined for this project as the following:

|------+-------------------|
| Code | Language          |
|------+-------------------|
| dan  | Danish            |
| gml  | Middle Low German |
| lat  | Latin             |
|------+-------------------|

** Text elements
The remaining elements present snippets of the text as found in the manuscript and are meant as a guide to the human reader of the catalogue rather than the computer. Only those elements which are found in the manuscript are used, meaning not all elements are required for each ~<msItem>~.

#+BEGIN_src xml
<rubric><!-- Rubric / heading --></rubric>
<incipit><!-- Incipit (first few words of main text) --></incipit>
<explicit<!-- Explicit (final few words of main text) --></explicit>
<finalRubric><!-- Final rubric (metatext in red or otherwise highlighted) --></finalRubric>
#+END_src

The element ~<rubric>~ gives the rubric (or heading) of a 
* Physical description (physDesc)
* History and provenance (history)
#+NAME: #history
