#+TITLE: Contents of Seven tyde unser lieven vrouwen (Arndes 1497)

* Transcription
** Rubric
Dat register desse bokes.

** Text
§ Jnt erste. eyne schone 

seghenynge des morge(n)s 

to leze(n)de mit de(n) (versiculus) vn(de) col(lecta)

§ Een seer ghut ghebet

va(n) vnser leue(n) vrouwen

in der sonne(n). Dar grot af

lath to gheuen is. § De

soue(n) dagetyde der iu(n)c-

—

frouwe(n) marie(n). § Alma

rede(m)toris to düde § Sal-

ue regina to düde § Re-

cordare tho düde. § De

soue(n) psalmen § De xv.

Pater noster § De(n) gul.

de(n) rosenkra(n)tz. § De viij.

krefftighe versche. de de 

duuel sunte bernde nicht 

gerne ape(n)barde. mit kor-

ter glosen vn(de) v(er)s(cul)i vn(de) col(lecta)

§ De vij bede van sunte

gregorius ape(n)baringe.

§ Va(n) der hylge(n) dreuol-

dicheit § Va(n) vnseme le-

—
uen here(n) ih(es)u (christ)o § Va(n)

vnser leue(n) vrowe(n) § Va(n) 

allen hyllighe(n) enghelen

§ Va(n) dyne(n) eghe(n) engel.

§ Va(n) sunte Johannes 

baptiste § Va(n) sunte Pe-

ter vn(de) Pawel. vn(de) vorta(n)

va(n) alle xij apostelen een 

sunderlich bet § Va(n) sun-

te Steffen erste merteler

§ Va(n) sunte Anthonio.

§ Va(n) su(n)te Sebastiano.

§ Va(n) su(n)te Jurge(n) § Va(n)

sunte Erasmo § Va(n) su(n)-

te Cristofero § Va(n) den 

—-

teyen dusent ridderen.

§ Va(n) sunte Laurencio

§ Van den xv. truwen

nothelpers. § Jnt ghe-

mene va(n) eyne(n) yuwelike(n)

merteler wor va(n) du wult

§ Va(n) sunte Jheronimo

§ Va(n) su(n)te Bonaue(n)tura

§ Jnt ghemene va(n) eme(n)

yuwelyken bychigher.

§ Van sunte Annen

§ Van sunte Elizabeth

§ Va(n) sunte Katherine(n).

§ Van sunte Barbare(n)

§ Va(n) sunte Margarete(n)

—

§ Va(n) sunte Dorotheen

§ Van sunte Gertrud.

§ Va(n) sunte Appolonien

§ Va(n) su(n)te Marie(n) mag-

dalene(n) § Va(n) sunte Ag-

nete(n) § Va(n) sunte agathe(n)

§ Va(n) de(n) xi dusent yunc-

frouwe(n) § Jnt ghemene

van eyner yu(n)cfrouwen

wor va(n) du wult. § Va(n)

alle gades hillige(n). § Va(n)

alle criste(n) zele(n) § Van de-

me pasche daghe. § Een

bed dat me(n) lest vnder de- 

—

me stylnisse § Vele scho-

noer bede we(n) du dat hyl-

lighe sacreame(n)te entfan-

ghest. Vn(de) we(n) du dat ent-

fanghe(n) hefst § Van den

hyllighe(n) dren ko(n)nynge(n).

§ Va(n) dem(e) antlathe vn-

ses leue(n) here(n). § Va(n) den

hyllighen vyf wunden.

§ Een seer ynnych bed

van groteme vordenste.

va(n) deme soete(n) name(n) ih(es)u

§ Een bed vor de pestile(n)-

cie. § De vyllige de me(n)

lyst vor de doden.
