#+TITLE: 15 Pater Noster
| Manuscript | AM 789 4to     |
| Locus      | 10r-10v, 1r-2v |
| Language   | Danish         |
 - NB :: Out of order in Manuscript

* Transcription
** Text 3
[[O]] [[J]]hesu (christ)e hi(m)merige læge(n) [[J]]ech hedrer

och signer thine mischu(n)delig øghne

for th(e)m ther all lønlige thingh obenbar-

res the th(e)r wærduge war(e) at felle thæ(r) for wor(e)

synder schyll ock the wor(e) spøttede aff iøderne h(er)re

gudh wændh myne øgne fraa all wærelzens gir(e)

och wlofflighet och giff mich wth atgyde thaare

bescheligh for mynesønder schyll *Ame(n)*

** Rubric
P(ate)r nost(er)

** Text 4
[[O]] [[J]]hesu criste sannelig ængle frælser Jech

signer och hedrer thin helge næse ther luc-

the then ondeluckt aff the [[R]]ower(e) kroppe

ther meth tigh hængde paa korsset Fforlad mich

alt thet jech hawer søndet modh tigh m(et) my(n) luck-

telsse och ladh mich kienne hwre sødh thu æst

*[[A]]men*

** Rubric
Pater noster Aue maria gratia plena

** Text 6

[[O]] [[J]]esu criste [[J]]ech hedrer och signer thine

helge læbe meth th(e)m thu wilde w(er)dughe

tich till ath my(n)ne thin uwen oc thin forræ-

dere [[J]]wdas [[G]]iff mich thin Nade J myne læbe fra(m)

at sige dagligæ thine ordh och forlad mich alt th(et)

iech hawer søndet m(et) my(n)æ læbe *Am(en)*

** Rubric
P(ate)r n(oste)r aue

** Text 7
[[O]] [[J]]hesu criste thu som glede er till all mys-

chwndh Jech hedrer oc signer thine helge

welsignede ørne the th(e)r hørde the forsmæ-

lige ordh och lastefwlle witne aff thine uwe(n)ner

ladh myne ordh ko(m)me till thine signde ørne ock

---[[https://handrit.is/manuscript/view/da/AM04-0789/20?iabr=on#page/10v/mode/1up][10v]]---

gøm myne ord fran alt onth [[A]]me(n)

** Text 8
[[O]] [[J]]esu criste hiærthens søthme oc glede

iech signer oc hederer thine rene och

milde hænder the ther war(e) gøme(n) sla-

ghene m(et) stor(e) jærne spighe [[J]]ech beder tigh at 

thw forladhe mich alt thet iech hawer søndet

modh tich m(et) myne hænder [[O]]ch giff mich rene

hænder och milde til thine thieniste och til tith

loff *[[A]]men*

** Text 9
[[O]] [[J]]h(es)u criste dygthelig h(er)re [[J]]ech hedrer

och signer thine helge arme the th(e)r 

ware wdrackte oc wddragne paa th(et)

helge kors for wore sønder schyl. Jech beder tik

at thu drage mich til tigh oc wnfaa migh m(et) 

thin signe kerlighet *[[A]]men*

** Text 10
[[O]] [[J]]h(es)u criste ther opbyriede dygdelighet 

i all dygt och fulko(m)melsse Jech hedrer 

och signer tith als(m)wisesthe bryst so(m)

all wisdom oc snille ær wdi støt och thet war

slaget m(et) harde 

** Text (?)
---[[https://handrit.is/manuscript/view/da/AM04-0789/1?iabr=on#page/1r/mode/1up][1r]]---

[[O]] [[J]]hesu criste alsom stærckeste løffue [[J]]ek

hedrer ock signer tich bræ(n)e(n)de hiærtte

ther thu haffde till mich th(e)r thu thet 

sønder skiffte for myne schyll [[J]]ech beder tich

at thu fulko(m)me thin kerlighet i mith hiertte

at iech motte tich ower alting ælske ame(n)

** Text (?)

[[O]] [[J]]hesu criste then høgste faders skiin

och fegerindhe [[J]]ech hederer och signer

thine helge knæ ther werdugethe th(e)m 

at falle til iorden thu th(e)r hellig(est) æst oc badh

sørghende til thin helge fader oc thu wasth

hørd i thin bøn [[J]]ech beder tig hør mich myn

søde ih(es)us i alle myne bøner ther mich ær(e) nøt-

teligh *[[A]]men*

** Text (?) 
[[O]] [[J]]hesu criste sanner ock fructsomeler [[J]]ek

signer och hederer thine helgø fød-

der the som fæste wor(e) meth nagle

och the werdugde thøm till atgaa om wærel-

den at thollæ mødeligt ærffuede for wor(e) hel-

snæ schyll [[T]]røste myne fødder på then rætte

wegh oc giff mich nade efft(er) at følge thinæ

fodspoor [[O]]ch forgiff mich alt thet iech haw(er)

meth myne fødder søndet modh tik ame(n)

** Text (?)
[[O]] [[S]]øde [[J]]h(es)u (christe) [[J]]ech hedhrer oc signer 

alle thine saar ther thu haffde poo

tith helge lego(m)me i thin pyne [[J]]ech

beder tich for tine dyr(e) saar ath thu frælsse

---[[https://handrit.is/manuscript/view/da/AM04-0789/2?iabr=on#page/1v/mode/1up][1v]]---

mich aff alle the saar iech hawer till my søn-

duge siel Amen

** Text (??)
[[O]] [[S]]øde [[J]]h(es)u (christe) iech beder tigh for thesse

bøner dygth(e)r schyll giff mich først

[[R]]ygelsse och hiærthens sorg for alle

myne sønder iech hawer modh tig søndet fra(m)

myn barndom ock størck mich i got leffnede

efft(e)r thin willie [[O]]c giff myne ve(n)ner oc fræ(n)-

der frælsse aff skerselds pine the th(e)r wdi

stedde ær(e) [[O]]ch the som i sønd ære at the skul-

le omwændes och størck th(e)m i godh stadughet

ther gode ær(e) Och giff my siel this helge lego(m)-

me til størcke oc til andelig føde oc thith helge

blod til rænselsse aff dødelig sonder oc thit

helge kors till wærnelsse for alle my(ne) uwe(n)-

ner [[O]]c werduge tigh till at ko(m)me m(et) thin

ker(e) moder maria J myn døtz thime oc tage

my siel oc lede he(n)ne til thet ewerdelig liff

och giff he(n)ne een særlig drick aff thin gud-

[[d]]oms kalk som thu hawer loffuet th(e)m ther

thesse bøner fulko(m)me gudelig *[[A]]me(n)*

** Rubric
[[T]]het war een hethe(r)lig qwi(n)ne och mærcke-

lig hwn atstwndethe at wide taal aff

gudz saar Och hwn bat gud ther om

at han schulle he(n)ne thet thee Gudh thedes for he(nne)

oc sagde Myne legoms saar the ware fæmtwsin

---[[https://handrit.is/manuscript/view/da/AM04-0789/3?iabr=on#page/2r/mode/1up][2r]]---

och fir(e) hundret och sextiwge Om thu wilt th(e)m

hedhre tha schalt thu hwær dag læse xv p(ate)r n(oste)r

oc xv Aue maria Tha areth ær omgangith

tha hawer thu hedreth hwart thet saar aa mit

legome war Hwilken thesse for(skreffne) bøner læs eth

aar om kringh hwær dag Aff hans slecth schal

frælses xv siele aff skiærsoldz pyne. oc xv søndu-

ghe me(n)niske schal omwendes. oc xv vise stad-

fæst(es) i gode giærni(n)ge oc stadugheit. oc selffuer

faar han fulko(m)melsse i dyght oc weth(e)rkie(n)nelsse

J hiærttet aff alle syne sønder Siden sagde gud

till he(n)ne hwo som thesse bøn[er ...]

ligh Jech schal hanu(m) giffue [...]

xv dage før han dør at han [...]

ewrdelig hwnger. oc aff m[...]

schal iech hanu(m) dricke giffu[e ...]

thørste ewinnelig. oc korssen [...]

for hanu(m) sætte till wærn for [...]

hans død schal iech ko(m)me m[...]

oc tage hans siel oc lede he(n)ne til then ewerde-

lig glede. oc tha hwn ær tidh ledh tha wil iech

skiæncke he(n)ne een særlig drick aff myn guddoms

kielde Siden schalt thu thet wide om nog(er) hafde

war(e)t stad i dødelig sønder thretwge aar och

wilde han læse thesse bøner tha wil iech hanu(m)

alle syne sønder forlade ther han haffde giort

aff sin barndom oc til th(en)n(e) thime han th(e)m

læs oc siden [scal han] war(e) bedre m(et) nade een

førr(e). Oc huat han bedes aff mich ell(e)r aff my(n)

moder maria th(et) schal ha(num) wides. oc siden.

schal iech lade ha(num) fulko(m)me i gudeligt leffnede

---[[https://handrit.is/manuscript/view/da/AM04-0789/4?iabr=on#page/2v/mode/1up][2v]]---

och stadfæste hans hiærtte i gode giærni(n)ge som ha(n)

haffde alle hans dage effter myn willie giort oc

leffnet Oc wilde iech hans liff længe om han J

morgen schulle døø Swo offte som thesse bøne siges

tha giffs fyr(e)tiwge dage afflat. oc hwo som thesse

bøner kie(n)ner noge(r) an(n)en hans glede oc hans

løøn schal øghes i hwær stadh Oc naar thesse bøne

læses tha er gudh nærwær(e)nd(is) oc gøm(m)er hanu(m)

fram alt ilt swo som han frælste s(an)c(t)e pouel aff

haffzens wode Amen
