#+TITLE: Hours of the Virgin (Matins)

|------------+---------------------|
| Manuscript | AM08-0073           |
| Work       | HOURS_VIRGIN.MATINS |
| Locus      | 44r 54v             |
| Language   | gml                 |
| Status     |                     |
|------------+---------------------|

* Transcription
** Incipit
[[3 red blue][D]]omine labia mea ape-

ries. et os meum an-

nunciabit laudem tua

** Text

[[2 blue][H]]ere opene myne lippen.

Vnde myn munt schal ku-

dighen dyn loff. [[red][G]]ot dencke

in myne helpe here snelle dy

my to helpende [[blue][E]]re sy deme

vadere deme sone vnde deme

hilghen geyste [[red][A]]lzo dat was

an deme antbegyne nu vnde

yummer bliuen scal Amen.

** Invitatory
*** Rubric
Inui(tatorium)

** Text

[[2 blue][I]]N de ere der saligen iuncuruwe

marie(n). Iubilere wy deme her

** Psalm                                                       :PSALM_97_v94:
*** Text

[[2 red][K]]omet wy vrowen vns

---44v---

to deme here(n) wy iubileren

gode vnseme heyle wy kome(n)

vor syn antlat mit loue vnde

iubilere(n) eme in den salmen.

[[red][I]]n der ere der saligen vts(upra) [[blue][W]]en-

te got is ey(n) grot here vnde ey(n)

grot koning boue(n) alle gode

wente de here vordriuet nicht

sy(n) volk. wente in syner hand

sint alle(n) ende der erde(n) vnde be-

schouwet de hoge der berghe

Jubilere wy deme here(n) [[red][W]]en-

te syn is dat meer vnde he

makede yd vn(de) de erde(n) stichtede(n)

syne hande komet vn(de) anbede

---45r---

wy ene vnde valle(n) vor got

vnde weyne(n) vor deme heren

de de vns geschape(n) heft wente

he is vnse h(er)e got mer my si(n)t

syn volk vnde schap syner

weyde [[red][I]]n de ere der saligen. vts(upra).

[[blue][O]]fte gy hudene syne stemp-

ne vorneme(n) so vorhardet

nicht iuwe herte also de lude

to der wostenye deden in deme

dage der bekoringe dar my

bekorede(n) iuwe vadere se pro-

ueden vnde segen myne werk

Jubilere wy deme here [[red][U]]er-

tich yar was ik negest desse-

---45v---

me slechte vn(de) sede alle tyd desse

de dwelet an deme herte(n) mer

se bekanden myner weghe

nicht. ik swor en in myneme

torne dat se nicht scholen in

myne rouwe ghan [[red][I]]n der ere

der salichsten iu(n)cvrowe(n). (et_cetera).

[[blue][E]]re sy deme vadere. deme

sone vnde deme hilgen geyste

also dat was in deme begy(n)-

ne vnde ewich bliuet Amen.

Jubilere wy deme heren. [[red][I]]n de ere

der saligesten iuncvrowe(n) mari-

en Jubilere wy deme heren.

** Psalm                                                            :PSALM_8:
*** Rubric

PSAlmus

---47r---

*** Incipit

[[2 red][D]]omine dominus noster.

*** Text
Here vn-

se here wo wunderlich

is dyn name in alle der erde(n)

[[red][W]]ente dyne welde is gebo-

ret boue(n) de he(m)mele [[blue][V]]te deme

munde der vnsprekende(n) kin-

dere dede noch sughen vullen

brochtestu dat lof dor dyne

viende dat du trostest den vi-

ant vnde den wrekere [[red][W]]en-

te ik scal seen dyne hemmele de

werke dyner vingere de(n) ma-

nen vn(de) de sterne(n) de du stichte-

dest [[blue][W]]at is de mynsche dat

du syner denckest ofte wat is

---47v---

des mysche(n) sone went du

ene vor wat rekenst [[red][W]]ente

du hefst ene eyn cleyn ge-

mynnet va(n) den engelen du

cronedest ene myt ere vnde

myt syrode vnde settest ene

bouen de werke dyner ha(n)de

[[blue][D]]u worpest alle ding vnd(er)

syne vöte schape vnde ossen

vnde dar en boue(n) alle quik

des veldes [[red][D]]es hemmels vo-

gele vnde des meres vissche

de dar des meres stighe wan-

deren [[blue][H]]ere vnse here wo wun-

derlik is dyn name in alle

---48r---

der erden [[red][E]]re sy deme vadere

*** Antiphon
**** Rubric
A(ntiphona)

**** Text

Du bist benedyet bouen alle

vrowen vnde benedyet is de

vrucht dines liues.

** Psalm                                                       :PSALM_19_v18:
*** Rubric
psalmus

*** Incipit
Celi enarrant gloriam

*** Text
De
hemmele kundeghet de ere
godes: vnde dat firmament
kundeghet de werke syner
hande De dach kundeghet
deme daghe dat wort vnde
de nacht kundeghet der nacht
de wisheyt It en sint nene
tunghen noch der men ere stemp
ne nicht ne horet En luth
gink in alle der erden vne [Page 48v]
ere wort ginghen in de ende
des ertrikes He sette syn tha
bernaculum in de sunne vnde
he gynk also eyn brudegam
van syner bedde kameren
He vrouwede sik also eyn
rese den wech to lopende
van deme ouersten hemmele is
syn ghank Unde syn wed
derghank beth to deme ho
gesten vnde nemant is dede
sik hudeth vor syne hitte
Des heren E is vnbesaluet
vnde bekeret de selen des heren
betuginge is lauelich vnde [Page 49r]
wisheit den cleynen Des he
ren rechticheit is recht vnde
vrowet dat herte dat luchtende
both godes is vorluchtende de
oghen Godes vruchte is hil
lich vnde bliuet in der werlde
der werlden des heren richte sin
was vnde sin in sik suluen
war vnde recht gemaket
Se sint begherlik bouen
golt vnde vele eddeler stene
vnde sotere bouen honnych
vnde seem Wente dyn knecht
bewaret se in der bewaringhe
der bode is vele wedder lones [Page 49v]
We vornympt de vorsumen
heit van mynen hemelken
reyneghe my vnde van den
vromeden schoue dyme knech
te Ofte se myner nicht ouer
herich ne werden so werde ik
vmbesaluet vnde werde ge
reyneget van deme grotesten
broke Unde mynes mundes
sproke werdet behegelik vnde
mynes herten trachtent wert
alle tijd in dyme angesichte.
Here myn helpere vnde myn
losere bist du Ere sy deme
vadere deme sone vnde.

*** Antiphon
**** Rubric
Anti(phona)

** Psalm                                                       :PSALM_24_v23:
*** Rubric
Psalmus

*** Incipit
Domini est terra

*** Text
Des heren
is dat ertrike vnde ere
vulle vnde allent dat dar ynne
wonet Wente he ene gestich
tet heft vp dat mer vnde heft
ene berede maket bouen de vlot
We stighet in des heren berch
edder we mach stan in syner
hilghen stede De vnschuldege
in den handen vnde reynes her
ten is de syne sele nicht geues
nam vnde de syme negesten nicht [Page 50v]
en swor in drogene Desse
scal nemen den sege van gode
vnde barmherticheit van go
de syneme heyle Dit is dat
slechte der genen de ene soket
dat antlat godes iacob Gy
vorsten vorhauet iuwe porten
vnde gy ewigen porten werdet
irhauen vnde de koning der
eren de scal dar inghan We
is desse koning der eren de starke
vnde de weldighe here de wel
dich is in deme stride Gy vor
sten irhauet iuwe porten vnde
gy ewighen porten werdey irhauen
[Page 51r]
vnde de koning der eren scal dar
inghan We is desse koning
der eren de here der dogede is ko
ning der eren Ere sy deme vadere.

*** Text
Singet vns sote sange vor deme
bedde desser iuncvrowen.

*** Versicle
**** Text
De
gnade is geghoten an dynen lippen.
Dar van benedye dy got ewichli
chen.

**** Text
Paater noster. Aue maria

** Lesson                                                          :LESSON_1:
*** Rubric
leccio princibus

*** Text
Sancta maria iuncvrowe
bouen alle iuncvrowen
moder vnde dochter des de eyn
koning is bouen alle koninge
gif vns dynen trost dat wy
van dyner wegen moten be
[Page 51v]
holden dat lon des ewighen leuen
des vnde dat wy mit dynen
wterkornen moten dat rike
beholden ewichliken. Sunder
du here wes vns gnedich.

*** Responsorium
**** Rubric
Responsorium

**** Text
Hilghe vnde vndbevleckede iunc
vrowe ik ne wet nicht mit wat
loue ik schal dy louen Wente den
de hemmel nicht begripen mochte
den drogestu an dyneme lichamme

*** Versicle
**** Rubric
versiculus

**** Text
Du bist benedyet bouen alle
vrowen vnde benedyet is de vrucht
dynes liues. Wente den.

** Lesson                                                          :LESSON_2:
*** Rubric
l. ijra.

*** Text
Sancta maria vnder allen
milden de mildeste. vnde vnd[er]
[Page 52r]
allen hilghen de hilgheste. De
wte dy gheboren is vnde is eyn
here bouen alle de hemmele de
sulue mote van dyner weghen
nemen vnse bede dat myt syner
leue mote delghet werden vnse
sunde. sunder du here wes vns
gnedich.

*** Responsorium
**** Rubric
Responsorium

**** Text
Salich bistu iuncvrow
maria de du den heren drogest den
schepper alle der werlden du wunnest
ene de dy schop vnde bleuest ewich
liken eyne iuncurowe.

*** Versicle
**** Rubric
versiculus

**** Text
Wes
ghegrot maria vnde alle gnade de
here is myt dy Du teledest den
de dy makede.

** Lesson                                                          :LESSON_3:
*** Rubric
lectio tercia

*** Text
Sancta maria wente du
werdich werest to vnt
fangende den alle de werlt
nicht begripen mochte delghe
vnse schult myt dinen milden
beden dat wy stighen mogen
to deme stole der ewygen ere
dar du mit dyme sone bist
ane ende. Mer du here wes
vns gnedich

*** Responsorium
**** Rubric
Responsorium

**** Text
Allerleueste
iuncvrowe godes werkersche der
dogeden Giff helpe den nottorfti
gen kum vrowe den to hulpe den
elenden dede to dy ropen.

*** Versicle
**** Rubric
versiculus

**** Text
Wente
wy vorducket werden myit der
[Page 53r]
sunden borden aller hilgheste wy
bidden dy. Gif helpe den
