#+TITLE: Sermo Angelicus (Revelationes Santæ Birgittæ liber XI)
#+AUTHOR: AM 70 8vo
| MS   | AM 70 8vo |
| Date | 1500      |

* Transcription
gantze jnnichliken van deme munde

des enghels. vnde wes se des daghes

heft ghescreuen dat deft se ghewiset

otmodeichliken alle daghe ereme ghest-

liken vader. Doch schach it dat de

enghel nichten quam in etliken daghe(n)

to vurderdichtinghe der lexien. Vnde in

deme daghe wenner er de vader vraghe

de war se ghescreuen hadde in deme

daghe do antworde se eme otmodich-

liken vnde sprak. Vader huten en hebbe

ik nicht ghescreuen. Wente ik hebbe

lange vorbeydet den enghel des heren

de my dichten scholde dat ik ghescreue(n)

hadde jn deme daghe he nichten quem

Vnde in sodaner mate so synt desse lexie(n)

de hir na volgen ghescreue(n) ut deme

munde des van der hoghen werdicheit

der juncvrouwen marien ghedichtet

vnde ghescreue(n). Vnde ok so wurden de

lexen ghedelet van deme enghele ouer

de weken. jewelikes daghes to lesende

in den metten dat gantze jar ouer al

se hir na volghet. Dar na so sprak

---1v---

de enghel. O ghy salighen sustere(n)

des ordens des hillighen salichmakers

vnde der regulen de he sulue(n) aller

salichmaker vnde schepper mit syne(re)

eghenen munde ghedichtet heft.

vnde jw vnde der werelt by syner brut

so gutliken vnde so otmodichliken ghe-

sant heft beredet de hant juwer hilli-

ghen werke de regele hillighen regele

to entfangende mit groter erwerdicheit

vnde junicheit. vnde desse hillighen

rede de juwer modher Sunte birgitte(n)

de enghel godes van deme hete vnses

heren heft ghesettet vnde ghedichtet

Opent juwe oren to horende also hoge

vnde eyn vnghehort nye loff der junc-

vrouwen marien. vnde ere hogheloff

dat ewich was. Vnde hw nv wert ghe-

reppet. Dencket myt otmodigheme

herten vppe dat ghy desse scrift mo-

ghen vlytliken smecken myt den kyn-

nebacken der hillighen auertrach-

tinghe. Vnde sijt jnuendich teende

ere sotticheit. jn den lustelike smak

---2r---

der gotliken biscouwinghe Vnde

dar neghest so bore vpp juwe hande

vnde juwe herte myt gantzer beghe-

ringhe to gade vnde gheuet em ju-

we otmoghe bet loff. |-vnde desse halli-

gherede-| vnde ere vor sodane woldat

de he juw sunderliken heft ghedan

Dar juw mote to sterken. vnde jw

ok mote gheuen marien eneborne

sone de konynk der enghele. De dar 

leuet vnde regneret myt marien

ewichliken vnde ju(m)mer ane ende Ame(n)

Jtem hir volghet na eyne Antiphona

van sunte birgitten

O birgitta ene mylde modh(e)r giff

milde arstedie den bedroueden

Jn desseme weghe leyde vns

auer dit duster meer dar wy moge(n)

seen clarliken de hemelschen dynghe

Bidde vor vns hillighe .~. versiculus

birgitta du gantze leue brut cristi

vppe dat he sy vns eyn recht wech to

deme hemelchen vader lande. ~

Collecta

---2v---

{W}od de du woldest vorluchten

dyne hillighe kerke vor myd

delst der hillighen vrouwen

Sunte Birgitten myt hillighen va

den vnde exemplen. Vorlye vns

gnedelike myt eren bede vppe dat dat

de dink de du vor vnse auertredinghe

gnedeliken hefft gheopenbaret myt

jnnichliken dancken moͤte vor volghe(n).

Dat sche dorch eme de dar is to kome(n)de

to richtende de leuendighen vnde de

doden vnde de werlt vormyddelst deme 

vure AmeN
