#+TITLE: Hours of the Virgin (Nones)

|------------+--------------------|
| Manuscript | AM08-0073          |
| Locus      | 80r                |
| Work       | HOURS_VIRGIN.NONES |
| Language   | gml                |
| Status     | Transcribed        |
|------------+--------------------|

* Transcription
** Rubric
(nonas)

** Text
Got dencke an myne helpe. here snelle my to helpende [E]re sy deme vadere.

** Text
[O] criste allerbarmh(er)tigeste [M]ari- a moder [E]re sy dy here vtsup(ra).

** Psalm
*** Rubric
p(salmu)s

*** Text
Se hebbe(n) my dicke an- gevochten van myner yo- get spreket isr(ae)l nu [D]e hebbe(n) yoget wente se mochte(n) myner nicht [D]e sundere smededen uppe myme rugge se vorlenge- de ere bosheit [D]e rechte here wil to sniden der sundere hals aderen se werde(n) vorstoret also

---80v---

de syon hateden vnde werde(n) to rugge keret [S]e werden also hoy der dake dat er vordorret wenne id wert wt getogen. [V]an deme he sine hande nicht voruullet de dit meyt vnder sine(n) schot de de garuen samlet [U]nde de dar vore gingen de enspreken nicht des heren be- nediginge sy bouen iw [W]y benedien iw in des heren name(n) [E]re sy deme vadere.

** Psalm
*** Rubric
Ite(m) p(salmu)s

*** Text
Here ik reep to dy wte der dupe here twide myne stempne [D]ine oren werden

---81r---

andencke(n)de an mynes bedes ste(m)p- ne [H]ere oftu beholdest de bos- heit here we mach dat doghe(n) [W]ente by dy is de gnedicheit vnde de dogede ik here dorch dine ee [M]yn sele dogede an syne- me worde my(n) sele hopede in de(n) heren [V]an der mettene tijd we(n)t an de nach hopede isr(ae)l an den heren [W]enste by deme here(n) is de barmherticheyt vnde vul losinge is by eme [U]nde he wil losen isr(ae)l wt alle(n) syne(n) bos heyde(n). [E]re sy.

*** Text
Here myn herte en is nicht vorhoget

---81v---

noch myne ogen sint nicht vor- heuen [N]och ich enwanderde nicht in der groten dinge(n) noch an den wunderlike(n) dingen bo- uen my [O]ft ik nicht an vor- nam otmodichlike(n) ich hogede myne zele [I]srahel hopede in den here(n) van desseme wente nu to ewighen tiden [E]re sy deme v.

*** Text
See maria du hest vns to der werlde(n) gebrocht den salichmaker den ioh(ann)es sach vnde sprak See dit is dat lam godes dat der werlde sunde dreghet.

** Chapter
*** Rubric
Capit(ulum)

*** Text
Ik vruchtede also eyn winstock mit soten roke vn(de)

---82r---

myne blome(n) syn blome(n) der ere vnde der werdicheyt. Gode sy gedanket.

*** Response
**** Rubric
R(espo)ns(orium)

**** Text
Help vns myt dine bede (Christ)i moder maria.

*** Versicle
**** Rubric
v(ersiculus)

**** Text
De du bist eyn bode des ewighe(n) leuendes vn(de) de darheit der hemele. (Christ)i moder. Ere sy de. Help vns.

*** Versicle
**** Rubric
v(ersiculus)

**** Text
Got help er mit syneme antlade. Got is vormid- delst er vnde wert nicht beweghet. Kyriel(eyson). (christ)el(eyson). Ky(rieleyson). Pater noster.

*** Collect
**** Rubric
Coll(ecta)

**** Text
Der hilghe(n) vnde der erlichen iuncvrowe(n) werdicheit. o h(er)e got mote vns alle tijd na vol- ghen vnde helpe(n) vns dyner gna- den. Dorch vnsen h(er)en ih(esu)m (christum).
