#+TITLE: Cantus Sororum (Matins)

|------------+---------------|
| Manuscript | AM08-0070     |
| Locus      | 3r            |
| Work       | CANTUS.matins |
| Language   | gml           |
| Status     | Transcribed   |
|------------+---------------|

* Transcription
** Text
bekoreden juwe vedere se prouede vnde

seghen myne werke. Quadraginta ¶

{U}ertich jar was ik by desser telinge

vnde sede alle tijt se dweleden an

deme herten. Men se bekanden nicht

myne weghe den ik hebbe sworen an

myneme torne se scholen nicht ghan

in myne rouwe. Gl(ori)a pat(ri) Ere sy de(me)

vadere vnde deme sone vnde deme hilli-

ghen gheste. Alse id was an deme

anbeghynne vnde nv vnde alle tid to

ewighen tiden Amen. ympnus. ¶

{O} du ere derhillighen drevaldicheit.

du syrnighe des hemelschen hoůes

du brut des allerhoghesten konynges

vnde ene moder synes sones Got de

heft dy ghehillighet van ambegy(n)ne

ene konynghynnen der ere vnde heft

dy vullenkomen maket ene vrouwe

bouen alle dingh. Hir vi(n)ne de hemele

dat ertrike dat mer vnde wat dar jnne

is. de louen dy myt rechteme rechte

alse a(n)name deme hoghesten heren

Du juncvrouwe alder a(n)nameste

---3v---

gode bouen alle dynk de he heft ghe-

schapen make vns anname eme de

he heft gheloset myt syme blode Ma0

ria du modher der gnadenmodher der

barmherticheit bescherme vns vor

den viand in der stunde des dodes nym

vns to dy. Ere sy dy here de du bist

gheboren van der juncvrouwen myt

⸠myt⸡ deme vadere vnde myt deme hilge(n)

geste to ewighen tyden Amen ¶

{O} du leflike juncvrouwe van gode

vp synen hillighen berch syon ge-

stedighet ene konyngynne make vns

denende dy neme sone in vrůchten

vnde ene hoghelouen myt beuynge

{W}or v(m)me gry(m)meden ¶psalmus

de lude: vnde dat volk de dachten

de ydelheit. De erdeschen ko-

nynge vnde de vursten quemen to

samen: jegen dan heren vnde tiegen

cristo. Wy breken ere bende: vnde wer-

pen van vns ere / De dar wonet

an den hemele de schal se bespotten:

vnde vns here schal se besch⸠e⸡⸌y⸍mpen

---4r---

De vne schal he to en spreken in syne(n)

torne: vnde in syme v(m)mode wil he se

bedrouen. Sunder ik byn eyn konynk

ghesettet van eme vpp synen hilligen

berch syon. to kůndeghen syn bot ~

Got sprak to my du bist myn sone:

huten ghebar ik dy. Bidde van my

ik gheue dy volk dyne erue: vnde de

ende der werelt stät an dyner walt.

Du scholt se righten an eyner yseren

roden: vnde schalt se to breken also

enen erdenen gropen Unde nv mer-

ket gy konynge: vnde werdet gheleret

gy de dar ordelen de erden. Deuet de(me)

heren myt vruchten: vn(de) vrouwet 

jw vor em myt beuynge. Gripet de

tucht vppe dat sik de here nicht en tor-

ne: |-vn(de) vorwe-| uppe dat. dat gy nichte(n)

vorgän van deme rechten weghe.

Wen er syn torne in korten bernet:

salich synt de. de an em louen. Ere

sy deme vader Antiphona.

{O} entfanger vnde ere der junc-

vrouwen. maria sta vp jegen

---4v---

vnse weddersaten. vnde dyne be-

nediginghe kome vppe dyn volk

{H}Ere wor v(m)me psalmus ¶

synt ghemeret de jene(n) de my

bedrouen: der is vele de my tiege(n)

stan Uele de seden dat in myner

selen were neyn heyle synes godes.

Sunder du here entfangest my:

du bist myn ere vnde vorhogest my(n)

houet. Jk rep to gode myt myner 

stempne. vnde he twide my van

synen hilligen berge. Ik slep vn(de)

rouwede vnde stunt vp wente got 

entfingh my. Jk schal nicht vru-

chten dusent volkes dat se my be-

gripen: here got staa vpp vn(de) make

my salich myn got. Uente du hest 

gheslaghen alle myne wedder sate(n)

my sunder sake: de tenen der sunder

hestu to broken Unses heren is

dat heil vnde vp dyne volk kome

dyn benediginghe. Ere sy deme

vader vnde deme sone vn(de) deme hil-

lighen gheste. Alse is(!) was (etc) ¶
