#+TITLE: Seven Penitential Psalms
** AM08-073_013r 
AM 73 8vo, f. 13r-
*** Parallel texts
Latin text with English translation: http://medievalist.net/hourstxt/penpss.htm
*** TOC
[[PSALM_6][Psalm 6: Domine ne in furore tuo arguas me.]]
[[PSALM_31][Psalm 31: Beati quorum remissae sunt iniquitates.]]
[[PSALM_37][Psalm 37 (38): Domine ne in furore tuo arguas me.]] 
[[PSALM_50][Psalm 50 (51): Miserere mei, Deus, secundum magnam misericordiam tuam.]]
[[PSALM_101][Psalm 101 (102): Domine, exaudi orationem meam, et clamor meus ad te veniat.]]
[[PSALM_129][Psalm 129 (130): De profundis clamavi ad te, Domine.]]
[[PSALM_142][Psalm 142 (143): Domine, exaudi orationem meam: auribus percipe obsecrationem meam in veritate tua.]]

*** Text
*Hir begynne(n) soue(n) salme(n)*

[[D]] _Omine ne in furo(r)e_ <<PSALM_6>>

_tuo arugas me: ne-_

_q(ue) in._ [[H]]ere en schelt

my nicht in dyneme vmmode

noch en tuchtige my in dyne-

me torne [[H]]ere gnade my

wente ich krank bin make 

my sunt: wente alle myne

knoke(n) bedrouet sint [[U]]nde

myne zele de is sere bedrouet

zunder du here wo lange [[B]]e-

kere dy here vnde loze mine

zele vnde make my salich dor

dine barmherticheit [[W]]ente

--- <<13v>> ---

nement de is in deme dode: de

dyner dechtik sin vnde we louet

dy in der hellen [[I]]k arbeyde yn

myner suchtinge ik wil wasche(n)

alle nacht my(n) bedde mit myne(n)

trane(n): vnde ik wil nat make(n)

myne leggerstede [[M]]yn oge

dat is bedrouet van v(m)mode ik

wart olt mank alle(n) mynen

vienden [[V]]aret van my alle

de dar werken de bosheyt -de- he-

re de heft getwidet de stemme

mynes bedendes [[D]]e here de heft

myn beide getwidet:vnde de here

heft myn beth entfange [[A]]lle

--- <<14r>> ---

myne viende de schame(n) sik:

vnde worde(n) bedrouet gar snel-

lichlik [[E]]re sy deme uadere

vnde deme sone: vnde deme 

hilgen geyste. Amen. *P(salmu)s* <<PSALM_31>>

[[B]] _eati quo(rum) remisse sunt_

_iniq(ui)tates_: [[S]]alich sint

de den ere bosheyt is vorgeue:

vnde ere sunde bedecket synt.

[[S]]alich is de man deme de h(er)e

nicht ene witet de sunde: noch 

in syneme geyste is nene dro-

gene [[M]]yne knoke(n) de sint vor-

oldet: wente ik gesprake(n) hebbe

do ik alle den dach rep [[W]]ente

--- <<14v>> ---

dach vnde nacht so is dyne 

hand geswaret bouen my ik

bin gekeret in myneme iare

also eyn dorne gestucket wert

[[I]]k dede dy witliche(n) myne bro-

ke: vnde behude nicht myne

vnrechticheit [[I]]k sprach wedder

my ik wil wasschen myne 

sunde: vnde bichte(n) se myneme

heren [[D]]at v(m)me so scal to dy

bidde(n) eyn yewelk hilge yn der

nottorftigen tijd [[I]]o doch in de-

me ouersten we veler lude so

scolen se dy ok nicht nalen.

[[D]]u bist myne toulucht in

--- <<15r>> ---

der drofnisse(n): de my heft v(m)me

vange [[I]]k wil dy geue(n) vorsta(n)t-

nisse: vnde wil dy wise(n) an den

wech den du gan schalt vnde

wil uppe dy stedigen myne o-

gen [[W]]erdet ok nicht alzo ey(n)

pert vn(de) eyn mule: in den nene

vorstantnisse en is [[U]]ele gey-

selen de sint des sunders sunder

barmherticheyt de scal ok vm-

megan alle de barmehertige(n)

de yn den heren hopen [[G]]y

rechten vrowet iw an den he-

ren: alle de van rechteme lo-

uen sint [[E]]re sy deme vadere

--- <<15v>> ---

vnde deme sone vnde deme hilge(n)

[[D]] _(omi)ne ne in fu-_ ยง geyste. <<PSALM_37>>

_rore tuo ar._ [[H]]ere en schelt

my nicht yn dineme vnmode:

vn(de) en berop my nicht in dyne-

me torne [[W]]ente dyne scho-

te de sint yn my gechicket:

vnde du hefst dine hant geste-

deget boue(n) my [[I]]n myneme

vlesche ene is nene zuntheyt                      [fn:ZUNTHEYT Lasch ยง330. I. /z/ for anlaut /s/ especially popular in west.]

van dyme antlate dines tornes

yn myne(n) knoke(n) is nen vrede

van deme antlate myner

sunde [[W]]ente myne bosheyt

de sind boue(n) my(n) houet gegan:

--- <<16r>> ---

vnde se sint geswaret bouen

my alzo ene sware bordene

[[M]]yne nare(n) de sint vorvult

vnde vordorue(n) van deme ant-

lade myner dumheit [[W]]ente

myne lende de sint voruullet

mit bespottinge: vn(de) in myne-

me vleysche en is nene sunt-

heit [[I]]k bin gepyneget: vnde 

alto zere geotmodiget van der

suchtinge mynes herte(n) [[H]]ere

vor dy is myne begeringe:

vn(de) my(n) suchtent dat ene is

vor dy nicht vorborge(n) [[M]]yn

herte dat is bedrouet vnde

--- <<16v>> ---

myne kraft de heft my vorla-

ten: vn(de) dat licht myner ogen

dat is nicht mit my [[M]]yne

vrunt vn(de) myne negesten de

stunde(n) wedder my: vnde deden

ok macht de myne zele sachte(n)

[[U]]nde my bose dink vragede(n) 

de hebbe(n) uppe ydelecheit gespra-

ken: vn(de) dachten alle den gan-                 [fn:GESPRAKEN Why <a> in participle?]

czen dach drogene [[S]]e ik was                       [fn:GANCZEN Note <cz> for /ts/] 

eyn doue de nicht en horde: vn(de)

de an syneme mu(n)de heft nene

sprake [[W]]ente ik hopede in

dy my(n) got here du scolt my 

twide(n): vnde also sik myne 

--- <<17r>> ---

viende bewegede(n). Se spreken                    [fn:SE S highlighted with red]

grote dink uppe my vn(de) hebbe(n)

gesprake(n) ydelicheit: vn(de) dach-

ten den ganczen dach droge-

ne [[W]]ente ik bin bereyde in

der geysele(n): vnde myne rode                    [fn:RODE 'suffering' -- what is this word? MDu hours WEE]

de is yu(m)mer an dyme angesich-

te [[W]]ente ik wil kundigen

myne bosheit: vnde wil denke(n)

uppe myne sunde [[M]]yne vie(n)de 

de leuet vn(de) sint gestedeget bo-

uen my: de my bosliken hate(n)

[[D]]e dar bose ding geue(n) v(m)me

de gude(n) de achter spreken my:

wente ik volgede der gude [[U]]or-

--- <<17v>> ---

lat my ok nicht here my(n) got:

ene vare ok nicht van my.

[[H]]ere got mynes heyles denc-

ke an myne hulpe [[E]]re sy

deme uadere vnde deme sone 

vn(de) deme hilgen geyste. Ame(n).                [fn:AMEN A highlighted with red]

[[M]] _Jser(er)e mei d(eu)s:_ [[G]]ot vor- <<PSALM_50>>

barme dy ouer my: na

dyner grote(n) barmherticheit.

[[U]]nde na ma(n)nichuoldicheit

dyner gnade: vnde delge my-

ne bosheit. [[U]]ortmer so was-

sche myne bosheyt: vnde rene-

ge my oc va(n) mynen sunden                       [fn:RENEGE Monophthongization of /ei/?]

[[W]]ente ik bekerme myne bos-

--- <<18r>> ---

heyt: vnde sunde de is yu(m)mer

tegen my [[I]]k hebbe dy allene

gesundeget vnde hebbe ouele

tegen dy gedan: dat du war-

dest gerichtet in dyne(n) reden

vn(de) vorwinnest wen du ok

werst richtende [[W]]ente ich 

bin entfange(n) in bosheyden:

vn(de) myne moder de entfink

my in den sunde(n) [[W]]ente du

hefst leff gehad de warheit:

vnde du heft my geopenbaret

de vnwysen vnde de vorbor-

gene dink dyner wisheit [[H]]e-

re besprenge my mit deme 

--- <<18v>> ---

ysopo: vnde ik warde gereyne-

get bouen den sne [[D]]u geuest

myneme horende vroude: vn(de)

de otmodigen bene de scolen

sik vrouwen [[K]]ere dyn ant-

lat van myne(n) sunde(n): vnde del-

ge myne bosheit [[G]]ot scheppe

an my eyn reyne herte: vnde

vornye yn myneme yngewe-

de eyne(n) rechte(n) geist [[U]]nde en

werp my nicht va(n) dyme ant-

lade: vnde nym my nicht dy-

nen hilgen geist [[G]]if my

wedder dynes heiles vroude:

vnde bestedege my mit dyme

--- <<19r>> ---

ersten geyste [[I]]k wil den bosen

dyne(n) wech leren: vn(de) de argen

de scholet to dy gekeret werde(n).                [fn:SCHOLET use of plural ending -et points westward]

[[H]]ere lose my van den zunde(n)

got mynes heyles: vnde myne 

tunge de scal dyne rechticheit

hoghen [[H]]ere du scalt myne

lippen up doen: vnde my(n) mu(n)t

de scal din loff kundigen.

[[H]]ere ofte du dat offer wol-

dest hebbe(n) gehad
