# Stabat Mater
AM 421 12mo

* Text
HOss korssens tree. m(et) sorg

oc wee. stood (christ)i mod(er).

med graadzens floder.

hennes søn paa korssyt hengde.

Aff sywck og graad. som ffør

war spaad. m(et) stoor wffryd.

stack drøwelzens sypd. he(n)nes

hierthe th(et) tha trengdhe. Hwad

sorg oc nød. aff (christ)ii død. gwdz

modh(e)r mw(n)ne ffa. th(e)r hw(er) th(et)

ssaa. syn /søn/ tha pynthes sa sare.

Hwn beeskelige greedh.

oc sorghede med. hw(n) styrthe 

ned. oc skaal tha wed. th(e)r han

skwlle lyde th(e)n fare. Hwær

soo haar. han ffell(e)r ey taar.

om han kwnde see. m(et) hwor

[30v] stor wee. Maria wed korssyth

pythes. Hwa saa syn søn

for me(n)niskes køn. wnd(er) swø-

we oc lyme. m(et) stoor beswyme.

meed reff tyl støtth(e)n bwndh(e)n.

TH(e)r han syn adn. gaff ffad(er)

j hand. oc sydh(e)n wdrand. bode

/blod/ oc wand. tha wor hw(n) nær for-

swndh(e)n. O Modh(e)r sødh. ffor

thyn søns død. thw wnd nw 

meg. at gredhe med tegh.

dijn sorch med tech at tech

at beræ. Gyff meg i synd.

ath legghe paa wind. ath

elske thyn søn. ssaa th(en)ne bøn

hannw(m) teckelige mothe ware.

UDij myth brysth. thw nw

[31r] yndkrytsh. hans wndh(e)r ffem.

ath tenke paa th(e)m. myn siel tyl

stor hwffswale. Lad /meg/ oc sa j

hierth(et) faa. bode willie oc hw. ath

htiene hannw(m) sa nw. thi hand

slig død tolle. O myldhe rooss.

lad meg sta hooss. oc bere meth

teg. aff drøffwelsse slig. som tha

tyth hierthe gesthe. O jomffrw

claar. hanss korss oc saar. hans

dødoc pyne. m(et) stytthe oc lyme.

dw y(n)nen myth hierthe festhe ~

Ieg wylle oc saa. motthe th(et) sa

gaa. i hierthe oc brysth. fra hand

oc toopp. hans saar oc hyd strygh

bere. Ieg bedh(e)r tegh nw. aff

hierthe oc hw. paa strenghe dom.

[31v] thw tyl megh kom. myth forswar

tha ath ware. Fra dieffwel-

sens swigh. thw frelsth tha megh.

lad hannw(m) ey tha. macth meth

megh ffaa. for thyn myskwnd oc

nadhe. O myldhe mø. naar jeg

skal dø. gack for tyn søn. medh 

modh(e)rlig bøn. oc frelss my(n) siel aff

waadhe Ame(n)
