#+TITLE: Ten Joys of Mary

|------------+--------------------------------|
| Manuscript | [[https://collections.library.yale.edu/catalog/2013366][Yale, Beinecke Library, MS 218]] |
| Locus      | 127r-134v                      |
| Language   | Low German                     |
|------------+--------------------------------|


** Parallels
|------------+---------|
| Danish     | MDB 105 |
| Low German |         |
| Latin      |         |
|------------+---------|

* Transcription
** Rubric
Ven den frouden vnser frowen

** Text 1
MAria Ik Vor-
mane dik der 
ouerflodigen
froude ere vn(n)d
werdicheit de
dyn zele. vnnd dyn lyff dar
van hefft entfangen. dat god
dy vader vnnd dy sone vnnd
dy hillige geist dik em(e) suluen
toeyner muder gaff. vnnd
alle der werlde. Jn deme rade
der hilligen driualdicheit. eer
he ye denn hemmel vnnd
erde schopp. Juncfrow ma(r)ia
---128r---
desser groten froude wes van
my armen sunde(re) vormanet
vnnd gebeden. entwide my
desser bede na dynen gnaden
vnnd na dyner barmhertig-
heit na myner begeringe vnd
na myner nottorfft Amen.

** Text 2
Maria ik vormane der
ouerflodigen froude
de dyn zele vnnd lyff entfingk
do dy de hilge engel sunte Ga-
briel kundigede. dattu goddis
muder werden scholdest vnnd
he sprak. Gegrutet sistu gna-
---128v---
den vul de herre is mit dy du
bist gebenediget mangk alle
den frowen. vnnd gebenediet 
is de frucht dines lyues. Do
du die wort wol vornemest
do bekandestu wol des vaders
gude. des sones barmhertig-
heit. des hilligen geistes wyss-
heit. Do sprekestu. Ik byn
eyne denerynne goddis. my
geschee na dynem willen.
Goddis wille de werde an
my fullenbracht. mit den
worden wordestu vorfullet
---129r---
mit dem hilgen geiste. vnnd
wunnest dynen sone sons
pyne dynes herten Vrouwe
dy maria goddis muder desser
groten froude der wes van
my armen sundere ermanet
vnnd gebeden vnnd getwide
my disser bede na dynen gna-
den. vnnd na dyner barmher-
tigheit. na myner begeringe
vnnd na myn nottorfft ame(n)

** Text 3
Maria ik vormane dy
der ouerflodigenn
froude ere vnnd wer-
---129v---
dicheit de dyn hilge zele vnnd
lyff entfyngk in den hilgen
wynachten dage. do dy dyn
leue kynt vroliken an der krib-
ben leidest vnnd bleuest ane
nod. vnnd ane smertte. vnnd
bleuest Juncfrowe vor der gebord
vnnd in der gebord. vnnd na der
bord vnnd ewich. Maria dy-
ne froude was so grod. do du
dyn leue kynt erst an segest
dat du id upp togest. Vnnd kus-
sedest dat vor synen munt.
dar ynne sprekestu Vrede sy
---130r---
den armen sundern. Sik fro-
wett dyner gebord allent dat
in hemmel vnd in erde is ma-
ria dissen groten froude wes
van my armen sund(er)e erman(et)
(et cetera) also vor gesc(reven) steit

*** Rubric 
Aue m(aria)

** Text 4
Maria ik vormane dik der
ouerflodigen groten
froude vnnd werdicheit de dyn
zele vnnd lyff entfyngk in de(n)
dritteynden dage na dynes 
kyndes geborth do de hilligen
dre koninge da opper brach-
ten. Wyrock mirren vnd golt
---130v---
wente se de ersten wern. de dyn
leue kynt erkanden. dat id god
vnnd mynsche was. Maria
desser groten froude (et cetera) alze vor(en).

** Text 5
Maria ik vormane dik der
groten ouerflodigenn
froude ere vnnd werdicheit
de dyn hilge zele vnnd lyff ent-
fingk. do du dyn leue kynt
wedder fundest in deme te(m)pele
dattu vorloren haddest in den
dridden dagh. vnnd wol wus-
test dat he den dod van den
yoden liden wolde. Daru(m)me
---131r---
was dyne froude deste groter
do du ene wedder fundest. Ma-
ria desser groten froude der
wes van my armen sundere
ermanet vnnd gebeden vn(n)d
getwide my dusser bede na dy-
nen gnaden. vnd na dyner
barmhertigheit na myner
begeringe vnd na myner not-
torfft Amen. 

*** Rubric
ghebet va(n) m(ari)a

** Text 6 
Maria ik vormane dy der
overflodigen grote(n) frou-
de vnd werdicheit de dyn zele
vnd lyff entfyngk in der hilge(n)
---131v---
passche nacht do dyn leue kynt
sick dick ersten opembarde na
syner hilgen vpstandinge.
Darna opembarde he sick sunte
marien magdalenen. vnnd
synen leuen Junghern. vnd
vor(e) weldichliken to der hellen
vnnd losede daruth alle de sy-
nen willen hadden gedan
vnnd vorede se mit sick in dat
paradiis dar se ynne won-
den wente to syner hemmel-
uart. Maria desser groten
froude des wes (et cetera) alzo vor(en)
---132r---

** Text 7
maria Ik vormane dy der
groten froude. de dyn zele
vnnd lyff entfingk. do dy(n) leue
kint to hemmel vor(e). mit alle
den de he an deme osterdage vth
der vorborgh der helle genome(n)
hadde. Maria dyne froude
was so grod. dat ik den frouden
nicht geliken magh. do du se-
gest dorch die negen kore der
hilgen engele. Vnnd segest vp
den stoll. de dik van der crafft
der hilgen dreualdicheit ge-
maket was. den du besitten
---132v---
scholdest. Maria desser grote(n)
froude der wes (et cetera) alse vor(en)

** Text 8
Maria ik vormane dik der
groten froude vnnd o-
uerflodicheit de dyn zele vnd
lyff entfingk an deme hilge(n)
pingest dage. do du vnnd de
hilge twelff apostelen. an
beslotener dore weren. do quam
dyn leue kynt midde(n) manck
vnnd sprak. Pax vobis. myn
vrede sy mit juk. dar worde
gy alle vorfullet mit deme
hilgen geiste. Do sandte dyn
---133r---
kynt twelff boden an die werlt
dat sie prediken scholden den
cristen gelouen. Maria der
groten froude vormane ik dy
vnnd twide my (et cetera) alze vor(en)

** Text 9
Maria ik vormane dy der
groten froude vnnd ere
de du entfengest. do dyn leue
kynt dy den hilgen engel sunte
Gabriel sande. dattu scholdest
van dessem elende scheiden to
der ewigen froude. dar queme(n)
de hilligen twelff boden tho
dyme leuendigen lyue. Dar
---133v---
quam dyn leue kynt mit alle
hemmelschen here to dynre
vorscheidinge. vnd vorde dik
mit lyue vnnd mit zelen in
de negen kore der hilgen enge-
le. dar wart dik van eyneme 
ioweliken engele grote ere ge-
boden. maria desser groten 
froude (et cetera) alze in dat erste

*** Rubric
or(ati)o

** Text 10
Maria ik vormane dick
der ouerflodigen froude
ere vnnd werdicheit. de dyn
zele vnnd lyff entfingk. do
dyn leue kint dik weldigliken
---134r---
vpnam. vnnd vorde dik mit sik
in den ouersten thron. vnnd
satte dik to synes vaders rech-
teren hant vp den stol der hil-
gen dreualdicheit. Vnnd gaff
dy gewaltt ouer hymmel vnd
erden. vnnd kronede dik mit
der kronen des rykes. vnnd mit
den twelff sternen. de dik her
salomon bereide. dar wordestu
geheiten eyne moder der barm-
hertigheit. Eddele iuncfrowe
maria. lath dyne barmher-
tigheit to mik schynen. vnnd
---134v---
twide mik desser bede. na dyne 
gnaden. vnnd na dyner barm-
herticheit Amen.
