#+TITLE: First Sunday of Advent

|------------+----------------------|
| Manuscript | Boek der Beschauwing |
| Locus      | 9 14                 |
| Work       | ADVENT_1             |
| Language   | gml                  |
| Status     | transcribed          |
|------------+----------------------|


* Transcription
** Rubric
Dyt les des ersten

so(n)dages in dem(e) ad-

uente

** Text
[[7][L]]Eue myn-

sche nu sc-

altu bede(n)-

ken wo de

hyllyghe

driualdy-

cheit vt sende de(n) starcke(n) Gabri-

el tho kundige(n)de der eddelen

iu(n)cfrouwen de heylsamegehn

bort, vn(de) de nygheit des ewige(n)

koninges. he gink dar de klen-

lyke iu(n)cfrouwe lach an ereme

bede vnde sprake to er. Wes ge-

---10---

grotet. Maria see du schalt ei-

nen sone entfange(n). dar verwu(n)-

derde se syk sere vore vn(de) sprak.

Wo schal dat scheen, ik beke(n)ne

neinen ma(n), de engel sprak. En

vruchte nicht, de hillige gheist

wil komen an dy. Alse efft he

sede. Maria en vruchte nycht

dyne kuschet hefft dem vader

so lustliken gewesen va(n) anbe-

ginne. dyn othmodicheit heft

godes sone so sere dwu(n)ge(n) dat

he wil va(n) dy gebaren werden.

Deme hilgen geiste heft dyne

hillicheit so wol behaget. dar

vm(m)me wyl he dy ouerulodigen

v(er)uullen. Do sprack se to deme

---11---

engele. See ik byn eine maget

godes. Se en en sede nicht ick

bin va(n) einem koni(n)glike(n) geslech-

te boren meer do se so grother

ere werdich was by gode dat

se de moder godes werde(n) schol-

de, vnde eine vrouwe he(m)melri-

kes vnde ertrykes de likede sik

ontmodichlike(n) eyner maget go-

des, Dyt is de erste tokumpst

godes alse he qua(m) va(n) de(n) he(m)mel

in dat ertrike to vns.

** Collect
[[4][A]]Alweldighe got de

du gehilget heft de

tid dyner eerlike(n) to-

ku(m)pst dat alle iarly-

kes de mynsche bedenke dat du

---12---

mynsche worde(n) bist. ick bidde

dy dorch dyne hylgen myn-

scheit willen dat ik de tyd di-

ner toku(m)pst also begynne(n) mo-

te vnde mit sodaner innicheit

vulle(n)bringe(n) mote dat du my

in dusser tid wedder ladest va(n)

alle den wege(n) de wedd(er) dy syn.

vn(de) make dine wege in my re-

cht also dat du an deme dage

diner borth werdelken an my

rowest, vnde dat huesz mines

herten bereit vindest dar geet

my an de gnade vn(de) soticheyt.

dat ick dy so sere dancke(n) mote

vor dyne kintheit vn(de) vor dy-

ne grote otmodicheyt dat du

---13---

doch my(n) heyl vor deme osse(n)

vn(de) esele woldest liggen an der

krybbe(n) dat du my deelaftich

makest alle dinen gude(n) werke

de du hest gewracht dre vnde

druttych yar vor mynn heyl,

vnnde alle des iamers den du

gehat hest va(n) der stu(n)de dyner

bort beth an de stunde dynes

dodes dat. ik dy an der kint-

heit also lauen mote. vnde my

an dyner marter so bedrouen

mote mit dy dat ik an dem vro-

liken dage diner hilge(n) vpstan-

dinge mit dy wedder vp stan

mote va(n) aller erdeschen beku(m)-

mernisse vn(de) na dusseme leue(n)de

---14---

dar kome(n) mote dar ik mit dy-

nen vtherkare(n) ewichliken leue(n)

mothe amen.
