#+TITLE: Magnificat

|------------+------------|
| Manuscript | Holm. A 42 |
| Locus      | 32r-32v    |
| Language   | Latin      |
|------------+------------|

* Transcription
[[M]]agnificat anima mea dominum; Et exultauit spiritus meus
in deo salutari meo; Quia respexit humilitatem ancille  
sue, ecce enim ex hoc beatam me dicent omnes generaciones. 
Quia fecit mihi magna qui potens est, et sanctum nomen eius, Et misericordia eius a progenie in progenies timentibus || eum. Fecit potenciam in brachio suo, dispersit superbos mente cordis sui, Deposuit potentes de sede et exaltauit humiles, Esurientes impleuit bonis et diuites dimisit inanes. Suscepit israel puerum suum recordatus misericordie sue, Sicut locutus est ad patres 
nostros, abraham et semini eius in secula. 
Gloria [patri. 
Sicut erat]. 
Ant. Sancta maria, succurre miseris, iuua pusillanimes, refoue flebiles, ora pro populo, interueni pro clero, intercede pro deuoto femineo sexu; [senciant omnes iuuamen tuum, quicumque cele- brant tuam commemoracionem. 
V. Domine, exaudi oracionem meam. 
R. Et clamor meus ad te veniat]. 
