#+TITLE: Transcription of Prayers in Org-Mode

* Metadata
The metadata for the file starts from the very beginning with the ~#+TITLE:~. Here the human-readable verison of the title is given, e.g. ~Hours of the Virgin (matins)~. This will be converted in TEI to the ~<titleStmt>~.

What follows is a table with the other metadata which will be placed inside the ~<fileDesc>~.

|------------+---|
| Manuscript |   |
| Locus      |   |
| Text       |   |
| Language   |   |
|------------+---|


- Manuscript :: Provide the key for the manuscript, e.g. ~AM08-0073~ for AM 73 8vo.
- Locus :: Provide the first and final page separated by a space, e.g. ~9r 9v~
- Text :: Provide the key for the text (if available), e.g. ~HOURS_VIRGIN.matins~ for Hours of the Virgin (matins)
- Language :: Provide the key for the language


* Transcription
The beginning of the transcription is marked with a top-level headline ~* Transcription~. This will mark the beginning of the ~<body>~ in TEI. 

** Text structure
Org-mode headings (indicated with asterisks) will produce nesting ~<div>~ tags in TEI. 

*** Special headers
The following headers are special:

- Text :: The main text.
- Rubric :: Any text in red either at the beginning or end of a main text.                   
- Incipit :: Latin incipits for texts in the vernacular. These are often underlined in the manuscript.
- Versicle :: 
- Respond ::
- Antiphon ::
- Lesson ::
- Chapter ::

# What about the orders for the Gloria Patri, etc?

** Mise-en-page
The following macros will be used to indicate the most salient features of the mise-en-page (layout) of the manuscript.

*** Lines and pages
A double hard return is used to indicate a new line, which will result in a ~<lb/>~ tag in the TEI. New pages are indicated with the folio number inside a triple-hyphen.

For example, the org-mode transcription:
#+BEGIN_SRC org
zele vnde make my salich dor

dine barmherticheit Wente

---13v---

nement de is in deme dode: de

dyner dechtik sin vnde we louet
#+END_SRC 

Results in:

#+BEGIN_SRC xml
<lb/> zele vnde make my salich dor
<lb/> dine barmherticheit Wente
<pb n="13v"/>
<lb/>nement de is in deme dode: de
<lb/>dyner dechtik sin vnde we louet
#+END_SRC

*** Enlarged and colored initials
Initial hierarchy can be important in distinguishing parts of a text. Enlarged and colored initials are placed inside a double-bracket ~[ [ ] ]~ which will automatically result in an underlined link in the org-file. These will be converted to ~<hi>~ tags in TEI.

It can be useful to include information about the color and height of initials. These can be done inside the first set of brackets with the number and color(s) separated by a whitespace. For example a three-line initial /M/ which is in red and blue (puzzle initial) can be indicated by encoding ~[[3 red blue][M~. In-line (single height) initials can be indicated simply by color, e.g. ~[[green][W~.

